/* =========================================================================
   KO II Coach — content layer
   Every device fact here targets the official teenage engineering EP-133
   K.O. II guide as of OS 2.5 (June 2026). Entries that could not be
   re-verified from this environment carry an `1` flag in the 4th slot and
   render with an "unverified" tag — see FIDELITY.md for the audit trail.
   ========================================================================= */

const META = {
  device: "EP-133 K.O. II",
  os: "2.5",
  checked: "2026-08",
  note: "content targets OS 2.5 — combos can change with firmware updates",
};

/* [category, keys, action, unverified?] */
const COMBOS = [
  ["Projects","Hold MAIN + pad 1–9","Switch to that project (a project = one song)"],
  ["Projects","Hold MAIN + pad 6–9","Open a factory-empty project to start clean (1–5 ship with demos)"],
  ["Scenes","Hold MAIN, then – / +","Move through scenes 01–99 (a scene = a section)"],
  ["Scenes","Hold MAIN + type a number","Jump straight to that scene"],
  ["Scenes","SHIFT + MAIN","Commit — freeze this scene and get a fresh copy to build on"],
  ["Song","Hold MAIN + ENTER","Open the song editor to chain scenes into an arrangement"],
  ["Song","SHIFT + GROUP A (in song editor)","Add a new scene slot to the song"],
  ["Song","SHIFT + – / + (in song editor)","Change which scene plays at this spot"],
  ["Song","SHIFT + PLAY","Play the whole song from the start"],
  ["Sounds","SOUND → group → pad","Pick a pad to load a sound onto"],
  ["Sounds","– / +  (in Sound)","Scroll samples on the selected pad"],
  ["Sounds","SHIFT + – / +  (in Sound)","Jump through samples ten at a time"],
  ["Sounds","Hold SOUND + type a number","Load a specific sample by number"],
  ["Sounds","Hold a pad (in Sound)","Preview the sample's name"],
  ["Sounds","SHIFT + SOUND","Sound Edit — trim, envelope, time-stretch, pan, play mode"],
  ["Sounds","Hold SHIFT + SOUND (2 sec)","Save your sound edits",1],
  ["Recording","Tap RECORD, then PLAY","Live record with a 4-beat count-in"],
  ["Recording","RECORD + PLAY together","Live record with no count-in"],
  ["Recording","Hold RECORD + a pad","Step-record that pad onto the current step"],
  ["Recording","RECORD, then SHIFT + PLAY","Record from the very start of the pattern"],
  ["Recording","Play, then hold RECORD + pads","Overdub onto a running pattern"],
  ["Recording","RECORD + ERASE + PLAY","Overwrite mode — replaces the old take as you record the new one"],
  ["Recording","Hold RECORD + move the FADER","Record fader (filter, level, etc.) movement"],
  ["Steps & length","Hold RECORD + – / +","Set pattern length (up to 99 bars)"],
  ["Steps & length","RECORD, then SHIFT + +","Duplicate the pattern and double its length"],
  ["Steps & length","– / +  (stopped)","Step forward / back through the pattern"],
  ["Steps & length","SHIFT + – / +","Move bar to bar"],
  ["Steps & length","Hold SHIFT + pad, then – / +","Nudge that note's timing"],
  ["Steps & length","Hold SHIFT + turn KNOB X","Set velocity of everything on the step"],
  ["Steps & length","Hold SHIFT + turn KNOB Y","Set note length on the step"],
  ["Keys","Select a pad, press KEYS","Play that sample across the pads like a keyboard"],
  ["Keys","Hold KEYS + – / +","Change octave"],
  ["Keys","Hold KEYS + a pad","Transpose — set the root note"],
  ["Keys","Hold TIMING + press pads (in Keys)","Arpeggiate the held pads — OS 2.5, one-shot & legato sounds"],
  ["Timing & groove","TIMING + turn KNOB X","Set the note interval (1/8, 1/16, triplets, 1/32…)"],
  ["Timing & groove","TIMING + turn KNOB Y","Add swing (works on 1/8 and 1/16)"],
  ["Timing & groove","TIMING, then – / +","Toggle quantize (–) vs free time (+)"],
  ["Timing & groove","Hold TIMING + a pad","Note repeat — perfect for hi-hats"],
  ["Timing & groove","TIMING, then SHIFT + pad","Latch note repeat on/off"],
  ["Timing & groove","SHIFT + TIMING","Timing Correct — quantize one pad, leave the rest"],
  ["Sampling","SAMPLE","Enter sample mode (the pads blink)"],
  ["Sampling","Hold a pad (in Sample)","Record to it; let go to stop (mono, up to 40 s on OS 2.5)"],
  ["Sampling","– / +  (in Sample)","Choose input: mic, line-in, resample, USB, L/R"],
  ["Sampling","Hold SHIFT + pad (in Sample)","Hands-free — the unit holds the pad for you"],
  ["Sampling","Hands-free, then PLAY","Resample the current pattern"],
  ["Sampling","SAMPLE (while recording)","Stop a hands-free sample"],
  ["Sampling","SHIFT + SAMPLE","Chop a sample across pads (auto or live)"],
  ["Sampling","In Chop: hold a group pad, then – / +","Choose auto-chop mode — EQU cuts equal-length slices (OS 2.5)"],
  ["Sampling","Hold SAMPLE + TEMPO","Detect incoming tempo and match the project to it"],
  ["Sampling","MAIN (in Sample)","Exit sample mode"],
  ["FX","FX (while playing)","Open the FX menu"],
  ["FX","– / +  (in FX)","Choose the effect"],
  ["FX","Move the FADER (in FX)","Set FX amount for the current group"],
  ["FX","Hold FX + a group pad","Solo that group (hold several to solo several)"],
  ["FX","Hold FX + pads","Punch-in FX — pressure-sensitive and combinable"],
  ["FX","SHIFT + FX","Output / master-compressor settings"],
  ["FX","SHIFT + FX, then +","Sidechain settings"],
  ["Copy · erase · undo","SHIFT + GROUP C","Copy (once = bar, twice = pattern)"],
  ["Copy · erase · undo","SHIFT + GROUP D","Paste"],
  ["Copy · erase · undo","SHIFT + GROUP B","Undo (umbrella lights when it's available)"],
  ["Copy · erase · undo","SHIFT + GROUP A","Jump to the next empty pattern"],
  ["Copy · erase · undo","Hold ERASE + a pad","Erase notes on that pad — even while playing"],
  ["Copy · erase · undo","Hold ERASE + a group pad","Erase the current pattern"],
  ["Copy · erase · undo","Hold ERASE + MAIN (2 sec)","Clear or delete the current scene",1],
  ["Copy · erase · undo","Hold ERASE + SOUND","Permanently delete the selected sample"],
  ["Copy · erase · undo","Hold ERASE + FADER","Erase the group's fader automation"],
  ["Tempo & loop","TEMPO","Enter tempo mode"],
  ["Tempo & loop","Tap TEMPO in rhythm","Tap tempo"],
  ["Tempo & loop","Hold TEMPO + type a number","Set exact BPM (40–399; use · for decimals)"],
  ["Tempo & loop","MAIN + TEMPO","Change the time signature"],
  ["Tempo & loop","SHIFT + TEMPO","Drop a loop (OB-4 style) on the fly"],
  ["Tempo & loop","Hold SHIFT + TEMPO","Set loop length — it ends when you let go"],
  ["Fader","Hold FADER + a pad","Assign the fader to the label above that pad (LEVEL, LPF, PAN…)"],
  ["Fader","Hold a group pad + move FADER","Set that group's overall volume"],
  ["Fader","SHIFT + FADER","Reset the fader's virtual position"],
  ["Sound Edit","SHIFT + SOUND","Enter Sound Edit — trim, envelope, pitch, play mode"],
  ["Sound Edit","Play mode (in Sound Edit)","Reverse a sample — flip its play direction (OS 2.5)"],
  ["System","SHIFT + ERASE","Open system settings"],
  ["System","Type 301 + ENTER","Pad velocity on, high sensitivity (ships off)"],
  ["System","Type 302 + ENTER","Pad velocity on, low sensitivity"],
  ["System","Type 300 + ENTER","Turn pad velocity off"],
  ["System","Type 400 + ENTER","Metronome on during record + play"],
  ["System","USB to computer / phone","Class-compliant USB audio in & out (OS 2.5)"],
  ["System","Hold MAIN while powering on","Lock mode — blocks changes until you restart"],
  ["System","Hold SHIFT + ERASE while powering on","Format the drive (fixes E.10–E.12; erases sounds)"],
];

const CTRL = {
  shift:{name:"SHIFT",sub:"the modifier",color:"#8f8778",
    blurb:"Held down, SHIFT unlocks a second function on almost every button — the small boxed label beneath it. It's the key to half the machine.",
    combos:[["SHIFT + SOUND","Sound Edit"],["SHIFT + MAIN","Commit a scene"],["SHIFT + SAMPLE","Chop"],["SHIFT + TEMPO","Drop a loop"],["SHIFT + ERASE","System settings"],["SHIFT + GROUP B","Undo"]]},
  sound:{name:"SOUND",sub:"assign & shape sounds",color:"#8f8778",
    blurb:"Where you put a sample on a pad and shape it. Pick a group, pick a pad, then scroll samples with – / +. SHIFT+SOUND opens deep editing — including reverse on OS 2.5.",
    combos:[["SOUND → group → pad","Choose a pad to load"],["– / +","Scroll samples"],["Hold SOUND + number","Load a specific sample"],["Hold a pad","Hear the sample's name"],["SHIFT + SOUND","Trim / envelope / time-stretch / reverse"]]},
  main:{name:"MAIN",sub:"home base",color:"#8f8778",
    blurb:"Your home screen — projects, scenes, patterns, recording and arranging all live here. Hold MAIN and the screen shows your scene (S.01…). When in doubt, press MAIN.",
    combos:[["Hold MAIN + pad 1–9","Switch project (song)"],["Hold MAIN + pad 6–9","Empty project"],["Hold MAIN, then – / +","Pick a scene"],["SHIFT + MAIN","Commit"],["Hold MAIN + ENTER","Song editor"]]},
  tempo:{name:"TEMPO",sub:"speed, loop & time-sig",color:"#8f8778",
    blurb:"Set the BPM by knob, by typing, or by tapping. Also hides the loop performance tool and the time signature.",
    combos:[["TEMPO + KNOB X","Set BPM"],["Tap TEMPO","Tap tempo"],["Hold TEMPO + number","Type exact BPM (40–399)"],["MAIN + TEMPO","Time signature"],["SHIFT + TEMPO","Loop"],["Hold SAMPLE + TEMPO","Match tempo to incoming audio"]]},
  sample:{name:"SAMPLE",sub:"record sound in",color:"var(--orange)",
    blurb:"Capture audio from the mic, the line-in (plug your guitar or phone in), USB, or by resampling the unit itself. Hold a pad to record onto it — mono, up to 40 seconds on OS 2.5. SHIFT+SAMPLE chops.",
    combos:[["SAMPLE","Enter sample mode"],["Hold a pad","Record; release to stop"],["– / +","Pick the input source"],["Hold SHIFT + pad","Hands-free recording"],["SHIFT + SAMPLE","Chop across pads"],["MAIN","Exit"]]},
  timing:{name:"TIMING",sub:"grid, swing & repeat",color:"#8f8778",
    blurb:"Sets the sequencer's note interval and swing, switches quantize on/off, and does note repeat when you hold it with a pad. In Keys mode it's also the arpeggiator (OS 2.5).",
    combos:[["TIMING + KNOB X","Note interval"],["TIMING + KNOB Y","Swing"],["TIMING, then – / +","Quantize vs free time"],["Hold TIMING + pad","Note repeat"],["SHIFT + TIMING","Quantize a single pad"],["In Keys: hold TIMING + pads","Arpeggiate (OS 2.5)"]]},
  keys:{name:"KEYS",sub:"play a sample melodically",color:"#8f8778",
    blurb:"Turns the pads into a chromatic keyboard for the selected sample — the fast way to play basslines and melodies. Hold TIMING with pads here to arpeggiate (OS 2.5).",
    combos:[["Select pad, press KEYS","Spread it across the pads"],["Hold KEYS + – / +","Octave"],["Hold KEYS + pad","Set the root note"],["Hold TIMING + pads","Arpeggiator (OS 2.5)"]]},
  fader:{name:"FADER",sub:"hands-on control",color:"#8f8778",
    blurb:"By default it's group volume. Reassign it and record its movement for automation. The silkscreen labels above the pads — LEVEL, PITCH, TIME, LPF, HPF, FX, ATK, REL, PAN, TUNE, VEL, MOD — are its possible destinations.",
    combos:[["Hold FADER + pad","Assign the label above that pad"],["Hold RECORD + move it","Record automation"],["Hold group pad + move it","Group volume"],["SHIFT + FADER","Reset it"]]},
  fx:{name:"FX",sub:"effects & punch-ins",color:"#8f8778",
    blurb:"Delay, reverb, distortion, chorus, filter, compressor — one per group via the fader. Hold FX and hit pads for live punch-in FX. SHIFT+FX is the master output.",
    combos:[["FX (playing)","Open FX"],["– / +","Choose the effect"],["Move FADER","FX amount"],["Hold FX + group","Solo it"],["Hold FX + pads","Punch-in FX"],["SHIFT + FX","Master compressor"]]},
  erase:{name:"ERASE",sub:"remove & undo territory",color:"#e9e7e0",
    blurb:"Removes notes, patterns, scenes or samples depending on what you hold it with. SHIFT+ERASE is the door to system settings.",
    combos:[["Hold ERASE + pad","Erase that pad's notes"],["Hold ERASE + group","Erase the pattern"],["Hold ERASE + MAIN (2s)","Clear the scene"],["Hold ERASE + SOUND","Delete the sample"],["SHIFT + ERASE","System settings"]]},
  groupa:{name:"GROUP A",sub:"suggested: drums",color:"var(--gA)",
    blurb:"One of four groups — think of each as an instrument with its own 12 pads and 99 patterns. A is the natural home for drums. The red tag is how it shows on the screen. Under SHIFT it's also 'next empty pattern'.",
    combos:[["Press A","Select the group"],["Hold A + – / +","Choose its pattern"],["SHIFT + A","Next empty pattern"],["Hold FX + A","Solo drums"]]},
  groupb:{name:"GROUP B",sub:"suggested: bass",color:"var(--gB)",
    blurb:"Second group — a good home for bass. Shows amber on the screen. Under SHIFT, GROUP B is your Undo button.",
    combos:[["Press B","Select the group"],["Hold B + – / +","Choose its pattern"],["SHIFT + B","Undo"],["Hold FX + B","Solo bass"]]},
  groupc:{name:"GROUP C",sub:"suggested: melody",color:"var(--gC)",
    blurb:"Third group — melodies and chords. Shows magenta on the screen. Under SHIFT, GROUP C is Copy.",
    combos:[["Press C","Select the group"],["Hold C + – / +","Choose its pattern"],["SHIFT + C","Copy (bar / pattern)"],["Hold FX + C","Solo melody"]]},
  groupd:{name:"GROUP D",sub:"suggested: your samples",color:"var(--gD)",
    blurb:"Fourth group — keep it empty for the sounds you sample yourself. Shows blue on the screen. Under SHIFT, GROUP D is Paste.",
    combos:[["Press D","Select the group"],["Hold D + – / +","Choose its pattern"],["SHIFT + D","Paste"],["Hold FX + D","Solo samples"]]},
  knobx:{name:"KNOB X",sub:"orange · context knob",color:"var(--orange)",
    blurb:"The context knob, sitting above SAMPLE. Its job changes per mode — BPM in tempo, note interval in timing, cutoff/drive in FX, amplitude in sound. Hold SHIFT while turning for fine control.",
    combos:[["In Tempo","BPM"],["In Timing","Note interval"],["In FX","First FX parameter"],["In Sound","Amplitude"],["Hold SHIFT + turn","Fine adjust"]]},
  knoby:{name:"KNOB Y",sub:"dark · context knob",color:"#8f8778",
    blurb:"The second context knob, above TIMING. Swing in timing, feedback/color in FX, pitch in sound, metronome volume in tempo. Hold SHIFT for fine control.",
    combos:[["In Timing","Swing"],["In FX","Second FX parameter"],["In Sound","Pitch"],["In Tempo","Metronome volume"],["Hold SHIFT + turn","Fine adjust"]]},
  volume:{name:"VOLUME",sub:"master output",color:"#8f8778",
    blurb:"Top-left knob — overall output level to the speaker and the output jack. Not part of any combo.",combos:[]},
  minus:{name:"MINUS  –",sub:"navigate down",color:"#e9e7e0",
    blurb:"With PLUS, the most-used pair on the unit: step through the sequencer, switch scenes and patterns, browse sounds and FX, nudge notes, change tempo.",
    combos:[["– (stopped)","Previous step"],["Hold MAIN + –","Previous scene"],["Hold RECORD + –","Shorten pattern"],["SHIFT + –","Previous bar"]]},
  plus:{name:"PLUS  +",sub:"navigate up",color:"#e9e7e0",
    blurb:"With MINUS, your main navigator: steps, scenes, patterns, sounds, FX, tempo and note nudging all run through it.",
    combos:[["+ (stopped)","Next step"],["Hold MAIN + +","Next scene"],["Hold RECORD + +","Lengthen pattern"],["SHIFT + +","Next bar"]]},
  record:{name:"RECORD",sub:"capture",color:"var(--orange)",
    blurb:"Arms recording. Tap it then PLAY for a counted-in live take, hit both together to skip the count, or hold it with a pad to place steps by hand.",
    combos:[["Tap RECORD, then PLAY","Live, with count-in"],["RECORD + PLAY","Live, no count-in"],["Hold RECORD + pad","Step-record"],["Hold RECORD + – / +","Pattern length"],["RECORD + ERASE + PLAY","Overwrite mode"]]},
  play:{name:"PLAY",sub:"start / stop",color:"#9a968c",
    blurb:"Starts and stops playback, bottom-right. Also the second half of most record moves.",
    combos:[["PLAY","Start / stop"],["RECORD, then PLAY","Record with count-in"],["SHIFT + PLAY","Play song from start"]]},
  enter:{name:"ENTER",sub:"confirm",color:"#8f8778",
    blurb:"Confirms typed values — sample numbers, system codes, tempo. Held with MAIN it opens the song editor.",
    combos:[["Type a code + ENTER","Confirm it"],["Hold MAIN + ENTER","Song editor"]]},
  pad:{name:"PADS  1–9, 0, ·",sub:"sounds + number pad",color:"#8f8778",
    blurb:"The 12 pads play your sounds and double as a number pad for typing values. The tiny silkscreen labels printed above each pad (LEVEL, PITCH, TIME, LPF…) are the fader destinations — assign one with FADER + that pad.",
    combos:[["Tap a pad","Play its sound"],["Hold RECORD + pad","Step-record it"],["Hold ERASE + pad","Erase its notes"],["Hold FADER + pad","Assign the fader"],["Type digits","Enter a number"]]},
};
["pad0","pad1","pad2","pad3","pad4","pad5","pad6","pad7","pad8","pad9","paddot"].forEach(k=>CTRL[k]=CTRL.pad);

/* Shift-box functions — opened by long-pressing the key that carries the box */
CTRL.sfedit={name:"EDIT",sub:"shift + sound · sound edit",color:"#e9e6df",
  blurb:"The boxed EDIT under SOUND. Hold SHIFT and press SOUND to open Sound Edit — trim start/end, shape the envelope, set pitch and time-stretch, pan, pick the play mode, and reverse a sample (OS 2.5).",
  combos:[["SHIFT + SOUND","Open Sound Edit"],["KNOB X / Y","Edit the shown parameter"],["– / +","Move between parameters"],["Play mode","One-shot, legato, loop… + reverse (OS 2.5)"],["Hold SHIFT + SOUND (2s)","Save the edits — unverified"]]};
CTRL.sfcommit={name:"COMMIT",sub:"shift + main · freeze a scene",color:"var(--orange)",
  blurb:"The orange COMMIT box under MAIN. SHIFT + MAIN freezes the current scene and hands you a fresh copy to keep building on — the K.O. II way to stack intro → verse → chorus without stopping.",
  combos:[["SHIFT + MAIN","Commit the scene"],["Hold MAIN, then – / +","Move between scenes"],["Hold MAIN + ENTER","Chain scenes in the song editor"]]};
CTRL.sfloop={name:"LOOP",sub:"shift + tempo · performance loop",color:"#b7b3aa",
  blurb:"The LOOP box under TEMPO. SHIFT + TEMPO drops an OB-4-style loop on the fly; hold the combo to set the loop length — it ends when you let go.",
  combos:[["SHIFT + TEMPO","Drop a loop"],["Hold SHIFT + TEMPO","Set loop length by holding"]]};
CTRL.sfchop={name:"CHOP",sub:"shift + sample · slice a sample",color:"#e9e6df",
  blurb:"The CHOP box under SAMPLE. SHIFT + SAMPLE slices a sample across a group's pads — automatically, evenly (EQU, OS 2.5), or live as you tap along.",
  combos:[["SHIFT + SAMPLE","Enter Chop"],["– / +","Number of slices"],["Hold a group pad, then – / +","Auto-chop mode — EQU = equal slices (OS 2.5)"],["Tap pads while playing","Live chop"],["KNOB X / Y","Fine-tune slice start / end"]]};
CTRL.sfcorrect={name:"CORRECT",sub:"shift + timing · fix one pad",color:"#e9e6df",
  blurb:"The CORRECT box under TIMING. SHIFT + TIMING opens Timing Correct — quantize the notes of a single pad and leave everything else exactly as you played it.",
  combos:[["SHIFT + TIMING","Timing Correct"],["Pick a pad","Quantize just that pad"]]};
CTRL.sfoutput={name:"OUTPUT",sub:"shift + fx · master section",color:"#e9e6df",
  blurb:"The OUTPUT box under FX. SHIFT + FX opens the master output settings — the master compressor, and the sidechain settings behind +.",
  combos:[["SHIFT + FX","Output / master compressor"],["then +","Sidechain settings"]]};
CTRL.sfsystem={name:"SYSTEM",sub:"shift + erase · settings",color:"#b7b3aa",
  blurb:"The SYSTEM box under ERASE. SHIFT + ERASE opens system settings — pad velocity, metronome, MIDI and sync, LED brightness, recording rates. Type a code and ENTER for quick access.",
  combos:[["SHIFT + ERASE","Open system settings"],["301 / 302 / 300 + ENTER","Velocity high / low / off"],["400 + ENTER","Metronome on"],["MIDI → Clock","Sync off / on / out"]]};

/* Rear connections + power — the tabs printed along the top edge */
CTRL.ptout={name:"OUTPUT",sub:"3.5 mm stereo out",color:"#eae7e0",
  blurb:"The main output jack — headphones or line out to speakers, a recorder, or an interface. The VOLUME knob sets its level (and the built-in speaker's).",
  combos:[["Turn VOLUME","Output level"],["Plug in phones","Speaker mutes, output continues"]]};
CTRL.ptin={name:"INPUT",sub:"3.5 mm sampling input",color:"#e8481c",
  blurb:"Where sound gets in — your guitar, phone, mixer, anything with a 3.5 mm line out. In Sample mode, pick line-in with – / + and set the gain with KNOB X (watch the level meter; CLIP means back off).",
  combos:[["SAMPLE, then – / +","Choose line-in (mono / stereo / L / R)"],["KNOB X (in Sample)","Input gain"],["Hold SAMPLE + TEMPO","Match project tempo to the input"]]};
CTRL.ptsyncmidi={name:"SYNC · MIDI",sub:"four 3.5 mm jacks · I/O · I/O",color:"#17140f",
  blurb:"Four jacks under one tab, marked I and O on the unit: sync in + out (PO-style pulse clock) and TRS MIDI in + out. The K.O. II can lead the clock or follow. No built-in Bluetooth — wireless MIDI needs a third-party BLE adapter.",
  combos:[["SHIFT + ERASE → MIDI → Clock","off / on / out"],["SYNC jacks","Pulse clock with POs & friends"],["MIDI jacks","TRS MIDI in / out to synths & DAWs"]]};
CTRL.ptusb={name:"USB",sub:"usb-c · power & data",color:"#8e8a80",
  blurb:"USB-C does nearly everything: powers the unit, moves samples with the EP Sample Tool, installs firmware updates, carries MIDI — and on OS 2.5, class-compliant USB audio in and out for phones, computers and DAWs.",
  combos:[["teenage.engineering/apps","EP Sample Tool + firmware updater"],["USB-MIDI","Notes light the MIDI/USB icons"],["USB audio (OS 2.5)","Record straight into a DAW or phone"]]};
CTRL.ptpower={name:"POWER",sub:"switch · usb-c or 4×AAA",color:"#e8481c",
  blurb:"The power switch on the top edge. Runs on USB-C or four AAA batteries (don't mix battery types). Two boot-time moves live here: hold MAIN while switching on for lock mode, hold SHIFT + ERASE while switching on to format the drive.",
  combos:[["Hold MAIN at power-on","Lock mode — restart to clear"],["Hold SHIFT + ERASE at power-on","Format (erases sounds; fixes E.10–E.12)"],["Battery icon","Lit on battery, blinks when low"]]};

/* =========================================================================
   Display icons — traced from the owner's photos of the real 128 MB unit
   (one at boot with every segment lit, one mid-session). Positions and
   existence come from the photos; meanings marked u:1 are not yet
   verified against the guide's screen page — see FIDELITY.md.
   ========================================================================= */
const DICONS = {
  tape:{name:"TAPE",sub:"top-left illustration",u:1,
    blurb:"The little red tape machine in the display's corner. It appears to be part of the K.O. II's animated scenes — likely tied to sampling and playback. Its exact behavior isn't documented in what I could verify; watch when it lights on your unit."},
  mute:{name:"MUTE",sub:"something is muted",u:1,
    blurb:"A speech bubble reading MUTE. Lights when a group is silenced — soloing groups with FX + a group pad mutes the others. If things go quiet unexpectedly, look here first."},
  keysic:{name:"KEYBOARD",sub:"keys mode",
    blurb:"The piano keys — lit when Keys mode is active and the 12 pads have become a chromatic keyboard for the selected sample. KEYS + – / + shifts octave; KEYS + a pad sets the root note."},
  whistle:{name:"WHISTLE",sub:"bottom-left illustration",u:1,
    blurb:"A tiny whistle-and-ball illustration in the lower corner — part of the display's playful scene artwork. Exact meaning not yet pinned down; tell me when you see it light."},
  padgrid:{name:"PAD GRIDS",sub:"one per group",u:1,
    blurb:"Four little dot grids, one beside each group letter. They appear to mirror the 12 pads of each group — showing activity and which pads hold sounds as patterns run. Watching them is the quickest read on who's playing what."},
  groups:{name:"GROUP TAGS  A–D",sub:"who's selected",
    blurb:"The four group letters in their colors — red A, amber B, magenta C, blue D. The selected group's tag lights. This is where the group colors live; the group keys themselves stay grey."},
  sync:{name:"SYNC",sub:"clock connection",
    blurb:"Lights when sync is in play through the SYNC jack — the K.O. II can send or receive clock. Configure it in system settings: SHIFT + ERASE → MIDI → Clock → off / on / out."},
  midi:{name:"MIDI",sub:"midi input",
    blurb:"The 5-pin DIN icon — lights when incoming MIDI notes are detected. MIDI clock and channel behavior live in system settings (SHIFT + ERASE)."},
  batt:{name:"POWER / BATTERY",sub:"power source",u:1,
    blurb:"The capsule icon by the connection row. The guide documents a battery icon that lights on battery power and blinks when low — this is very likely it (a USB-power indicator is the other candidate)."},
  bar:{name:"BAR",sub:"position: bars",
    blurb:"Labels the big number when it shows your position — the readout counts bar.beat.tic, and patterns run up to 99 bars. BAR + TIC frame where you are in the loop."},
  copy:{name:"COPY",sub:"shift + group c",
    blurb:"Lights when you copy — SHIFT + GROUP C. Once copies the bar, twice copies the whole pattern. Pair with PASTE on SHIFT + GROUP D."},
  paste:{name:"PASTE",sub:"shift + group d",
    blurb:"Lights when you paste what COPY grabbed — SHIFT + GROUP D. The bar-or-pattern distinction follows what you copied."},
  save:{name:"FLOPPY DISK",sub:"saving",u:1,
    blurb:"The floppy — almost certainly the auto-save indicator. The K.O. II saves your work continuously (commit is a snapshot, not a save), so expect this to flicker as you edit."},
  tic:{name:"TIC",sub:"position: ticks",
    blurb:"The other half of the position readout — bar.beat.tic. When the big number reads 1.1.1 you're at the very top of the pattern."},
  digits:{name:"THE BIG NUMBER",sub:"the main readout",
    blurb:"The display's centerpiece — three segment digits showing whatever matters right now: position (1.1.1), scene (S.01), BPM, sample numbers in Sound mode, system codes, and error codes (E.xx) if something's wrong."},
  bpm:{name:"BPM",sub:"tempo readout",
    blurb:"Lights when the big number is showing the tempo — set it with KNOB X in Tempo mode, tap it on TEMPO, or type it: hold TEMPO + a number (40–399, · for decimals)."},
  meter:{name:"LEVEL METER",sub:"signal level",
    blurb:"The bar-graph VU for the current signal. Watch it while setting sampling gain with KNOB X — hot but clean, and if CLIP lights you've gone too far."},
  watch:{name:"STOPWATCH",sub:"timing",u:1,
    blurb:"A stopwatch by the tempo cluster — plausibly the tempo-match/listening indicator (hold SAMPLE + TEMPO and the unit listens, finds the tempo, and sets the project to it). Not yet verified."},
  stereo:{name:"STEREO",sub:"input channel mode",
    blurb:"Sampling input mode — line-in can capture stereo, mono, or a single channel (L/R). Cycle the input with – / + inside Sample mode; MONO lights for single-channel capture."},
  mono:{name:"MONO",sub:"input channel mode",
    blurb:"The mono half of the input-mode pair — lit when sampling in mono (mono up to 40 s on OS 2.5). STEREO lights for two-channel capture."},
  gauge:{name:"COLOR WHEEL",sub:"four-part dial",u:1,
    blurb:"The big four-color circular dial — its quarters match the group colors. It appears to be a value/level dial that fills as you turn knobs or move the fader. Exact behavior not yet verified against the guide."},
  rgrid:{name:"DOT MATRIX",sub:"right-side grids",u:1,
    blurb:"Pixel-grid blocks on the display's right side — they light in patterns during play and edits. Likely step/value readouts for the current mode; not yet verified in the guide."},
  art:{name:"PIXEL ART",sub:"corner illustration",u:1,
    blurb:"The multicolor pixel artwork in the display corner — part of the K.O. II's animated scenes (TE gave this display real personality). Decorative-plus: it changes with what you're doing."},
  metro:{name:"METRONOME",sub:"the click",
    blurb:"Blinks in time with the metronome. Turn the click on for record + play with system code 400 (SHIFT + ERASE first); its volume is KNOB Y in Tempo mode."},
  chopic:{name:"SCISSORS",sub:"chop",
    blurb:"Scissors — the chop indicator. SHIFT + SAMPLE slices a sample across a group's pads: auto, evenly (EQU, OS 2.5), or live as you tap."},
  umb:{name:"UMBRELLA",sub:"undo is available",
    blurb:"The famous umbrella — lit when an undo is available. SHIFT + GROUP B takes the last thing back. One level deep, so use it while it's lit."},
  note:{name:"NOTE",sub:"note value",u:1,
    blurb:"The note glyph — tied to the sequencer's note interval (1/8, 1/16, triplets, 1/32…), set with TIMING + KNOB X."},
  trim:{name:"TRIM",sub:"sound edit",u:1,
    blurb:"Waveform-with-brackets — the sample trim view in Sound Edit (SHIFT + SOUND), where you set a sample's start and end points."},
  env:{name:"ENVELOPE",sub:"sound edit",u:1,
    blurb:"The ramp — the envelope stage of Sound Edit: attack and release shaping for the selected sample (also reachable per-pad via fader destinations ATK / REL)."},
  stretch:{name:"TIME / STRETCH",sub:"sound edit",u:1,
    blurb:"Part of the Sound Edit family — the K.O. II can time-stretch samples to fit the project tempo. TIME is also a fader destination (above pad 9)."},
  rec:{name:"REC DOT",sub:"recording",
    blurb:"The red dot — lit while recording: live takes, step recording, fader automation, hands-free sampling. RECORD then PLAY counts you in with 4 beats."},
  play:{name:"PLAY",sub:"pattern running",
    blurb:"Lit while the sequencer runs. PLAY starts and stops; SHIFT + PLAY plays the whole song from the top."},
  loopic:{name:"LOOP ARROW",sub:"cycling",u:1,
    blurb:"The circular arrow — loop/cycle. Likely lit while the pattern loops or the SHIFT + TEMPO performance loop is held; not yet verified which."},
  arrow:{name:"BIG ARROW",sub:"unidentified",u:1,
    blurb:"A bold arrow next to the transport icons. Candidates: the reverse indicator (OS 2.5 added sample reverse) or a nudge/move marker. Not yet verified — tell me when you see it light."},
  fx:{name:"FX",sub:"effects",
    blurb:"Lit in FX territory — pick an effect with – / + in the FX menu, send the group in with the fader, and punch effects live by holding FX + pads (pressure-sensitive, stackable)."},
  tube:{name:"TUBE",sub:"drive",u:1,
    blurb:"A little vacuum tube — almost certainly tied to the drive/distortion flavor in the FX section. Not yet verified against the guide's icon list."},
  faderic:{name:"FADER",sub:"fader activity",u:1,
    blurb:"The slider glyph — fader movement/assignment. The physical fader defaults to group volume; hold FADER + a pad to point it at the label above that pad."},
  q:{name:"Q · QUANTIZE",sub:"snap to the grid",
    blurb:"Quantize — with Q lit your hits snap to the note interval set in TIMING. Press TIMING then – to quantize, + for free time (the FREE label beside it)."},
  free:{name:"FREE",sub:"no grid",
    blurb:"Free time — the opposite of Q. Press TIMING then + and the sequencer records exactly what you play, no snapping. TIMING then – brings the grid back."},
  soundic:{name:"SOUND",sub:"mode label",
    blurb:"Lit in Sound mode — picking and loading samples onto pads. SOUND → group → pad, then – / + to scroll the library."},
  phones:{name:"HEADPHONES",sub:"monitoring",u:1,
    blurb:"The headphone glyph beside MAIN — likely the output/monitoring indicator (the output jack doubles for phones). Not yet verified."},
  mainic:{name:"MAIN",sub:"mode label",
    blurb:"Home base — lit whenever you're in Main mode, where playing, recording, scenes and songs happen. Lost? Press MAIN."},
  burst:{name:"BURST",sub:"the asterisk",u:1,
    blurb:"The starburst between MAIN and TEMPO — the same ✳ printed on GROUP A's key. On the key, SHIFT + A jumps to the next empty pattern; what the on-screen burst signals isn't verified yet."},
  tempoic:{name:"TEMPO",sub:"mode label",
    blurb:"Lit in Tempo mode — BPM by knob, tap, or typed number (hold TEMPO + digits, 40–399), plus the time signature via MAIN + TEMPO."},
  eraseic:{name:"ERASE",sub:"mode label",
    blurb:"Lights when erasing — hold ERASE with a pad to strip its notes (even mid-playback), with a group pad to wipe the pattern, with SOUND to delete a sample for good."},
  systemic:{name:"SYSTEM",sub:"mode label",
    blurb:"Lit inside system settings (SHIFT + ERASE) — velocity, metronome, MIDI/sync, brightness, recording rates. Type a code + ENTER for quick access: 301 velocity, 400 metronome."},
  clip:{name:"CLIP",sub:"too hot",
    blurb:"The red warning triangle — the input is clipping. Back the sampling gain off with KNOB X; a clipped take stays clipped."},
  swing:{name:"SWING",sub:"groove amount",
    blurb:"The little swing signature — lit when swing is in play. TIMING + KNOB Y adds it (works on 1/8 and 1/16 grids) and pulls the beat off the grid politely."},
};


/* =========================================================================
   LEARN — 32 guided lessons from the content library (ko2-content-library.md).
   [BRACKETS] render as key chips and **bold** as <b> via FMT() in app.js.
   levels: Basics · Core · Advanced
   ========================================================================= */
const RECIPES = [
  /* ---- Basics ---- */
  {cat:"Concepts",level:"Basics",t:"Understand the structure",s:"How the K.O. II thinks, in one minute",
   steps:["A **project** is one song — you have 9 slots.",
     "Inside it are four **groups** ([A]–[D]) — think drums, bass, melody, your samples — each with 12 pads.",
     "A **pattern** is a sequence for one group (up to 99 bars).",
     "A **scene** is all four groups' current patterns playing together — one section.",
     "A **song** chains scenes into an order."],
   tip:"When you feel lost, press [MAIN] — that's home, where projects, scenes and recording live."},
  {cat:"Drums",level:"Basics",t:"Make your first beat, live",s:"New project to a committed loop in a minute",
   steps:["Hold [MAIN]+[pad 6] for a clean, empty project.",
     "[SOUND] → [GROUP A] → tap a pad → dial in a kick with [–]/[+]. Fill a few pads with drums.",
     "[MAIN], then tap [RECORD] then [PLAY] — you'll hear a 4-beat count-in.",
     "Play the pads to punch out a beat. [PLAY] stops.",
     "Like it? [SHIFT]+[MAIN] to commit it as a scene."],
   tip:"Pads feel flat? Velocity ships off — [SHIFT]+[ERASE], type 301, [ENTER]."},
  {cat:"Sounds",level:"Basics",t:"Load and audition sounds",s:"Get the right sounds under your fingers",
   steps:["[SOUND] → pick a group → tap the pad you want to fill.",
     "Scroll with [–]/[+]; hold [SHIFT]+[–]/[+] to jump ten at a time.",
     "Remember the map: kicks **1–99**, snares **100–199**, hats **200–299**, perc **300–399**, bass **400–499**, melodic **500–599**.",
     "Hold a pad to preview a sample's name."],
   tip:"Build a kit across the pads before you sequence — it's faster than swapping sounds mid-flow."},
  {cat:"Timing",level:"Basics",t:"Set tempo and time signature",s:"Get the clock right first",
   steps:["[TEMPO], then turn [KNOB X] for a rough BPM.",
     "For an exact value, hold [TEMPO] and type it (40–399; [·] for decimals).",
     "Tap [TEMPO] in rhythm to set it by feel.",
     "Need 3/4 or 6/8? [MAIN]+[TEMPO] changes the time signature."],
   tip:"Set tempo before you record — changing it later is fine, but starting right saves re-feel."},
  {cat:"Feel",level:"Basics",t:"Turn on velocity and play with dynamics",s:"Make the pads respond to your touch",
   steps:["[SHIFT]+[ERASE] to open system settings.",
     "Type 301, [ENTER] (that's velocity ON; 300 is off).",
     "Now record and vary how hard you hit — accents land loud, ghost notes sit soft."],
   tip:"Per-step control too: on a step, [SHIFT]+[KNOB X] sets velocity, [SHIFT]+[KNOB Y] sets length."},

  /* ---- Core ---- */
  {cat:"Drums",level:"Core",t:"Program a house beat by step",s:"Exact placement, no timing skills required",
   steps:["[MAIN], hold [SHIFT]+[–] to reach step **1.1.1**.",
     "Hold [RECORD] + kick pad on **1.1.1**, **1.2.1**, **1.3.1**, **1.4.1** (four-on-the-floor).",
     "Add a clap/snare on **1.2.1** and **1.4.1** (backbeat).",
     "Add hats on the off-beats."],
   tip:"Set the grid first — [TIMING]+[KNOB X] for 1/16, then place."},
  {cat:"Drums",level:"Core",t:"Program a boom-bap hip-hop beat",s:"Laid-back and swung",
   steps:["Kick on 1 and the 'and' of 2-ish; snare hard on 2 and 4.",
     "Steady 1/8 hats.",
     "[TIMING]+[KNOB Y] to add swing so it leans back.",
     "Vary hat velocity for a human feel."],
   tip:"Nudge a snare slightly late ([SHIFT]+pad, then [–]/[+]) for that behind-the-beat pocket."},
  {cat:"Drums",level:"Core",t:"Program a trap beat with rolling hats",s:"Fast hats without the finger cramp",
   steps:["Lay a slow kick pattern and a snare/clap on beat 3.",
     "Put hats on a pad; hold [TIMING] + that pad for note repeat.",
     "Change the repeat rate with [KNOB X] mid-roll for triplet bursts.",
     "[TIMING] then [SHIFT]+pad latches the roll hands-free."],
   tip:"Ride the fader on the hats' volume while rolling for classic trap dynamics."},
  {cat:"Feel",level:"Core",t:"Add swing and groove",s:"Get the beat to breathe",
   steps:["[TIMING] + turn [KNOB Y] to add swing (1/8 and 1/16).",
     "A little pushes the groove; too much drags — dial to taste.",
     "Toggle quantize off ([TIMING] → [+]) for even looser feel."],
   tip:"Swing the hats more than the kick/snare for a natural bounce."},
  {cat:"Feel",level:"Core",t:"Add ghost notes and dynamics",s:"The difference between a demo and a groove",
   steps:["With velocity on, record your main hits hard.",
     "Add quiet in-between snare/hat hits (ghost notes) at low velocity.",
     "Nudge a few notes slightly off-grid for life."],
   tip:"Fix any that land too loud per-step with [SHIFT]+[KNOB X]."},
  {cat:"Arrangement",level:"Core",t:"Build a fill",s:"End your 4 or 8 bars with a moment",
   steps:["Duplicate/extend the pattern so you have a spare bar ([RECORD]+[+]).",
     "On the last bar, add a snare roll or tom run (note repeat helps).",
     "Drop an element out just before the fill for contrast."],
   tip:"Commit the fill version as its own scene so you can drop it in only when you want it."},
  {cat:"Bass & melody",level:"Core",t:"Play a bassline in Keys mode",s:"Turn one sample into an instrument",
   steps:["Select a bass pad, press [KEYS] — the pads become a chromatic keyboard.",
     "[KEYS]+[–]/[+] changes octave; [KEYS]+pad sets the root note.",
     "Record it live or by step."],
   tip:"Keep basslines simple and locked to the kick; space is your friend."},
  {cat:"Bass & melody",level:"Core",t:"Write a melody or chords in Keys mode",s:"Get a hook going",
   steps:["Put a melodic sample on a pad, press [KEYS].",
     "Find a short motif — 3–5 notes is plenty.",
     "Set the sample's play mode to legato in sound edit for smooth lines."],
   tip:"Match the melody's key to your bass root so they agree."},
  {cat:"Bass & melody",level:"Core",t:"Use the arpeggiator",s:"Instant motion from held notes (OS 2.5)",
   steps:["Enter [KEYS] mode.",
     "Hold [TIMING] and press multiple pads — they arpeggiate.",
     "Works when the sample's play mode is one-shot or legato."],
   tip:"Change step rate with the timing knob to reshape the arp on the fly."},
  {cat:"Sampling",level:"Core",t:"Sample your guitar (or any instrument)",s:"Get real playing into the box",
   steps:["Plug into the 3.5 mm input (or use the built-in mic).",
     "[GROUP D] → [SAMPLE] → [–]/[+] to choose line-in. Set level with [KNOB X].",
     "Hold an empty pad and play your riff; release to stop. Tap the pad to audition.",
     "[MAIN] to exit and sequence it."],
   tip:"Hold [SAMPLE]+[TEMPO] while playing so the project matches your riff's tempo."},
  {cat:"Sampling",level:"Core",t:"Sample from your phone or another source",s:"Grab a loop, a vocal, anything (line-in)",
   steps:["Cable your source into the input; [SAMPLE] → [–]/[+] → line-in.",
     "Set gain with [KNOB X] so it's strong but not clipping.",
     "Hold a pad to capture; release to stop."],
   tip:"Sample a couple of extra seconds — you can always trim tight afterward."},
  {cat:"Sampling",level:"Core",t:"Hands-free sample yourself",s:"When you need both hands",
   steps:["In sample mode, set input, gain and threshold.",
     "Hold [SHIFT] + a pad to start hands-free — the K.O. II holds the button.",
     "Sing/play/strum; press [SAMPLE] to stop."],
   tip:"The threshold lets recording trigger on the first sound so you don't capture silence."},
  {cat:"Sampling",level:"Core",t:"Resample your whole beat to one pad",s:"Free up voices or mangle the mix",
   steps:["Get your pattern playing.",
     "Jump into [SAMPLE] and choose the resample source (or start sampling while it plays).",
     "Capture the pattern to a new pad, then chop or FX it as one sound."],
   tip:"Use [–]/[+] in hands-free to grab an exact number of bars."},
  {cat:"Sampling",level:"Core",t:"Chop a breakbeat",s:"Turn a loop into playable slices",
   steps:["Get a loop onto a pad; [SHIFT]+[SAMPLE] to enter Chop.",
     "Pick an empty group for the slices (it overwrites that group's pads).",
     "Auto-chop: [–]/[+] sets slice count — on OS 2.5, hold a group pad and pick **EQU** with [–]/[+] for equal-length slices. Or LIVE chop: tap pads in time to place cuts.",
     "Refine each slice's in/out with [KNOB X]/[KNOB Y]."],
   tip:"Re-order the slices across the pads to invent a brand-new groove."},
  {cat:"Sampling",level:"Core",t:"Choose where a sample lands",s:"Stay organized",
   steps:["Hold [SOUND], type a slot number on the pads (e.g., 3·0·3), [ENTER].",
     "Now hit [SAMPLE] and record — it goes to that slot."],
   tip:"Reserve slots by type so your kits stay tidy across projects."},
  {cat:"Sound edit",level:"Core",t:"Trim a sample tight",s:"Cut straight to the good part",
   steps:["[SHIFT]+[SOUND] → Trim.",
     "[KNOB X] = start point, [KNOB Y] = length.",
     "Hold [SHIFT] while turning to zoom in for fine edits."],
   tip:"To make the cut permanent and save space, hold [SHIFT]+[SOUND] in the Trim page — but it's destructive."},
  {cat:"Sound edit",level:"Core",t:"Shape a sound with the envelope",s:"Snappy or soft, your call",
   steps:["[SHIFT]+[SOUND] → Envelope.",
     "[KNOB X] = attack (fade-in), [KNOB Y] = release (tail vs. hard cut).",
     "Short attack + short release = punchy; slow attack = pad-like swell."],
   tip:"A touch of release on drums glues them; too much makes them wash out."},
  {cat:"Sound edit",level:"Core",t:"Set play mode and choke your hats",s:"Make hats behave like real ones",
   steps:["Select a sound, [SHIFT]+[SOUND].",
     "Set play mode: one-shot (drums), key/gated (hold to sustain), legato (smooth melodic).",
     "Put open + closed hats in the same mute (choke) group so one cuts the other."],
   tip:"Choke groups also work for anything that shouldn't overlap — like alternate vocal chops."},
  {cat:"Sound edit",level:"Core",t:"Time-stretch a sample to your tempo",s:"Fit a loop to the project",
   steps:["[SHIFT]+[SOUND] → TIME.",
     "Match the sample's BPM to the project; the time-stretch indicator lights when active."],
   tip:"For big tempo changes, expect some character change — sometimes that's the sound you want."},

  /* ---- Advanced ---- */
  {cat:"Arrangement",level:"Advanced",t:"Build a song with commit + scenes",s:"Stack sections without stopping",
   steps:["Get a loop you like.",
     "[SHIFT]+[MAIN] — commit. It freezes the scene and hands you a copy.",
     "Change the copy (fill, mute, new sound); commit again.",
     "Repeat to stack intro → verse → chorus as scenes."],
   tip:"Commit is not 'save to disk' (that's automatic) — it's 'snapshot this and give me a fresh copy.'"},
  {cat:"Arrangement",level:"Advanced",t:"Arrange scenes in song mode",s:"Turn sections into a track",
   steps:["Hold [MAIN]+[ENTER] to open song mode.",
     "Add scene slots and set which scene plays at each position.",
     "[SHIFT]+[PLAY] plays the song from the top."],
   tip:"Song position is independent of scenes, so you can reuse a chorus scene many times."},
  {cat:"Workflow",level:"Advanced",t:"Copy and paste patterns and bars",s:"Reuse without redoing",
   steps:["[SHIFT]+[GROUP C] copies (once = a bar, twice = the pattern).",
     "Move to the destination and [SHIFT]+[GROUP D] to paste."],
   tip:"Copy a solid 1-bar groove, paste it across bars, then vary just the last one."},
  {cat:"Performance",level:"Advanced",t:"Record fader automation",s:"Movement that plays itself back",
   steps:["Assign the fader: hold [FADER] + a pad (filter, level, FX send…).",
     "Hold [RECORD] and move the fader as it plays.",
     "Erase just that automation with [ERASE]+[FADER]."],
   tip:"A slow filter open across 8 bars is an easy, satisfying build."},
  {cat:"FX & mixing",level:"Advanced",t:"Add send effects per group",s:"Space and color",
   steps:["[FX] → [–]/[+] to pick delay, reverb, distortion, chorus, filter, or compressor.",
     "Raise the [FADER] to send the current group in.",
     "One send per group — choose what each part needs most."],
   tip:"A short delay on a lead and a little reverb on the snare go a long way; don't drown everything."},
  {cat:"Performance",level:"Advanced",t:"Perform with punch-in FX",s:"The K.O. II's signature party trick",
   steps:["Start playback.",
     "Hold [FX] — the 12 pads become momentary, pressure-sensitive effects.",
     "Stack them for stutters, filters, tape-stops and glitches.",
     "Hold [RECORD] while you perform to keep the moves."],
   tip:"Practice one effect at a time; muscle memory here is what makes live sets feel alive."},
  {cat:"FX & mixing",level:"Advanced",t:"Set up sidechain (kick ducks bass)",s:"Make room in the low end",
   steps:["[SHIFT]+[FX] → [+] to reach sidechain.",
     "Choose the source: hold a group pad, pick the sound (usually the kick).",
     "Choose the destination groups: [SHIFT] + the group pads (usually the bass)."],
   tip:"A subtle duck cleans up mud; a heavy one becomes an audible pump — both are valid looks."},
  {cat:"Setup",level:"Advanced",t:"Sync the K.O. II to other gear",s:"Play in time with the rest of your rig",
   steps:["Connect via SYNC (pulse) or MIDI in/out over the TRS jacks or USB.",
     "Decide who's the clock leader and set the other to follow ([SHIFT]+[ERASE] → MIDI → Clock).",
     "Start the leader; the follower locks to its tempo."],
   tip:"Bluetooth isn't built in — a third-party BLE MIDI adapter adds wireless, but wired stays rock-solid."},
];

/* =========================================================================
   STUCK — 77 Q&A entries from the content library (ko2-content-library.md).
   {cat, p: question, c: optional context, d: the answer/fix}.
   [BRACKETS] render as key chips via FMT() in app.js.
   ========================================================================= */
const FIXES = [
  /* ---- First steps ---- */
  {cat:"First steps",p:"How do I start a brand-new, empty project?",
   d:"Hold [MAIN] + a pad 6–9. Those four projects ship empty (1–5 hold factory demos). Your other projects stay untouched."},
  {cat:"First steps",p:"How do I switch between whole projects (songs)?",
   d:"Hold [MAIN] + tap a number pad 1–9. Note: holding [MAIN] and using [–]/[+] moves through **scenes**, not projects — the number pad is what changes the project."},
  {cat:"First steps",p:"What's the difference between a project, group, pattern, scene, and song?",
   d:"**Project** = one song (9 slots). **Group** = one of four instruments, [A]–[D], each with 12 pads. **Pattern** = a sequence for one group (up to 99 bars; up to 99 patterns per group). **Scene** = a snapshot of every group's current pattern playing together = one section. **Song** = scenes chained into an order."},
  {cat:"First steps",p:"Where's the save button? Do I need to save?",
   d:"There isn't one — the K.O. II auto-saves constantly. 'Commit' ([SHIFT]+[MAIN]) is not save; it snapshots the current scene and hands you a fresh copy to keep building on."},
  {cat:"First steps",p:"How do I put a sound on a pad?",
   d:"[SOUND] → pick a group → tap a pad → scroll samples with [–]/[+]. Or hold [SOUND] and type a sample number to jump straight to it."},
  {cat:"First steps",p:"I hit pads in project 6 and nothing happens",c:"Projects 6–9 are empty from the factory.",
   d:"Load sounds first: [SOUND] → group → pad → [–]/[+]."},
  {cat:"First steps",p:"What do the four groups mean — do I have to use them a certain way?",
   d:"No rules, but the suggested layout is A = drums, B = bass, C = melody, D = your own samples. Each group is independent, with its own 12 pads and its own patterns."},

  /* ---- Recording & editing ---- */
  {cat:"Recording & editing",p:"How do I record live?",
   d:"Tap [RECORD] then [PLAY] for a 4-beat count-in, or hit [RECORD]+[PLAY] together to start instantly. Play the pads; press [PLAY] to stop."},
  {cat:"Recording & editing",p:"How do I place hits one step at a time (no timing skill needed)?",
   d:"Stop playback, use [–]/[+] to move to a step, then hold [RECORD] + a pad to drop that sound on the step."},
  {cat:"Recording & editing",p:"How do I make my pattern longer than four bars?",
   d:"Hold [RECORD]+[+] to add bars (up to 99); [RECORD]+[–] removes them. To double a loop you already made, press [RECORD] then [SHIFT]+[+] — it duplicates the pattern into the new length so you can vary the second half."},
  {cat:"Recording & editing",p:"How do I erase one wrong note?",
   d:"Hold [ERASE] + the pad — works even while playing. Hold several pads to clear several at once."},
  {cat:"Recording & editing",p:"How do I wipe an entire pattern?",
   d:"Hold [ERASE] + the group pad."},
  {cat:"Recording & editing",p:"How do I clear a whole scene?",
   d:"Hold [ERASE]+[MAIN] for about two seconds."},
  {cat:"Recording & editing",p:"I made a mistake — how do I undo?",
   d:"[SHIFT]+[GROUP B]. There's a single level of undo; the umbrella icon on screen lights when one is available."},
  {cat:"Recording & editing",p:"My new recording is layering on top of the old one — how do I overwrite instead?",c:"Recording overdubs by default.",
   d:"To replace as you go, start recording in overwrite mode: [RECORD]+[ERASE]+[PLAY], then play the new take."},
  {cat:"Recording & editing",p:"How do I set how hard or soft a step hits?",
   d:"On the selected step, hold [SHIFT] + turn [KNOB X] for velocity. [SHIFT] + [KNOB Y] sets the note's length."},
  {cat:"Recording & editing",p:"How do I nudge a note slightly off the grid for feel?",
   d:"Hold [SHIFT] + the pad, then [–]/[+] to move that note's timing."},
  {cat:"Recording & editing",p:"My pads ignore how hard I hit them",c:"Velocity sensitivity is OFF from the factory.",
   d:"[SHIFT]+[ERASE], type 301, [ENTER]. (300 turns it back off; 302 = low sensitivity.)"},
  {cat:"Recording & editing",p:"How do I copy and paste a pattern or a bar?",
   d:"[SHIFT]+[GROUP C] copies (once = one bar, twice = the whole pattern); [SHIFT]+[GROUP D] pastes."},
  {cat:"Recording & editing",p:"I want a fresh pattern to try an idea without losing this one",
   d:"[SHIFT]+[GROUP A] jumps to the next empty pattern for that group."},

  /* ---- Scenes & song ---- */
  {cat:"Scenes & song",p:"I've made a bunch of loops — now what? How do these become a song?",
   d:"Commit them into sections. [SHIFT]+[MAIN] snapshots the current scene and gives you a duplicate; change something (add a fill, mute a part), then commit again. Stack scenes this way, then hold [MAIN]+[ENTER] for song mode and chain them in order."},
  {cat:"Scenes & song",p:"What exactly does 'commit' do, and why does everyone talk about it?",
   d:"It saves the current scene **and** duplicates it, so you can freely change the next section's patterns without losing what you had. Think of it as version control for your arrangement — and you never have to stop the music."},
  {cat:"Scenes & song",p:"How do I move between scenes?",
   d:"Hold [MAIN], then [–]/[+] (or type a scene number)."},
  {cat:"Scenes & song",p:"How do I use a different pattern for one group inside a scene?",
   d:"Hold that group's pad + [–]/[+] to select its pattern."},
  {cat:"Scenes & song",p:"My pattern numbers jump around unpredictably as I commit scenes",c:"That's normal — committing spins up new patterns and the numbering isn't strictly sequential.",
   d:"Don't chase pattern numbers; think in scenes (sections) instead. The pad settings and sequences are what matter."},
  {cat:"Scenes & song",p:"How do I set the actual song order / arrangement?",
   d:"Hold [MAIN]+[ENTER] to enter song mode. Add scene slots and set which scene plays at each position; [SHIFT]+[PLAY] plays the song from the top. Song position is independent of scenes, so you can reorder freely."},

  /* ---- Sample library ---- */
  {cat:"Sample library",p:"Where do my recorded samples live? Are they stuck to one project?",
   d:"They go into one global sample library (up to 999 slots / 128 MB). A sample you record is available to **any** project — only the pad assignments are saved per project."},
  {cat:"Sample library",p:"How are the built-in sounds organized?",
   d:"By type and number: kicks **1–99**, snares **100–199**, hi-hats **200–299**, percussion **300–399**, bass **400–499**, melodic **500–599**."},
  {cat:"Sample library",p:"How do I delete a sample I don't want?",
   d:"In [SOUND] mode select it, then hold [ERASE]+[SOUND]. This removes it from the device permanently."},
  {cat:"Sample library",p:"How do I see a sample's name?",
   d:"In [SOUND] mode, hold the pad. Names only exist for samples you imported or renamed with the EP Sample Tool; factory/recorded ones may just show a number."},
  {cat:"Sample library",p:"How do I get my own WAVs onto the device?",
   d:"Connect over USB-C and use the EP Sample Tool (teenage.engineering/apps/ep-sample-tool) to upload, name, and organize samples."},
  {cat:"Sample library",p:"Can I run out of space?",
   d:"Yes — 999 samples or 128 MB, whichever comes first. Delete unused samples to make room. Lower-sample-rate files take less space."},

  /* ---- Sampling ---- */
  {cat:"Sampling",p:"How do I sample something?",
   d:"Press [SAMPLE], use [–]/[+] to pick the input (mic, line-in, resample, USB), hold a pad to record, release to stop. [MAIN] exits."},
  {cat:"Sampling",p:"How do I sample when I need both hands (guitar, singing)?",
   d:"Hands-free sampling: in sample mode hold [SHIFT] + a pad to start, play/sing, then press [SAMPLE] to stop. Set your gain and threshold first so it captures cleanly."},
  {cat:"Sampling",p:"How do I sample my whole beat down to one pad (resample)?",
   d:"Set the input to 'resample', or just jump into sampling while the pattern is playing — it samples the current pattern. Great for freeing up voices or mangling the full mix as one sound."},
  {cat:"Sampling",p:"How do I sample an exact number of bars?",
   d:"With hands-free sampling engaged, press [–]/[+] to choose the number of bars, then press [PLAY]."},
  {cat:"Sampling",p:"How do I choose which slot a new sample lands on?",
   d:"Hold [SOUND], type a number on the pads (e.g., 3·0·3), press [ENTER], then hit [SAMPLE]."},
  {cat:"Sampling",p:"How do I match a sampled loop to my project's tempo?",
   d:"Hold [SAMPLE]+[TEMPO] to detect the incoming tempo, or use TIME (time-stretch) in sound edit to conform it."},

  /* ---- Sound edit ---- */
  {cat:"Sound edit",p:"How do I cut the silence or junk off the front/back of a sample?",
   d:"[SHIFT]+[SOUND] → Trim. [KNOB X] sets the start point, [KNOB Y] sets the length. Hold [SHIFT] while turning to zoom into a ~1-second window for precision."},
  {cat:"Sound edit",p:"How do I make a trim permanent (and save space)?",
   d:"In the Trim page, hold [SHIFT]+[SOUND] to crop the file on disk. This is destructive and can't be undone, so trim a copy if you're unsure."},
  {cat:"Sound edit",p:"How do I make a sound snappier, or give it a fade-in or a tail?",
   d:"Envelope in sound edit: [KNOB X] = attack (fade-in), [KNOB Y] = release (let it ring vs. cut off hard). Snappy snares, soft pads — all here."},
  {cat:"Sound edit",p:"How do I change a sample's pitch or pan?",
   d:"In sound edit each sound has its own pitch/tune and pan (plus level and envelope), independent of the others."},
  {cat:"Sound edit",p:"What are play modes — one-shot, key, legato?",
   d:"One-shot plays the whole sample per tap (good for drums). Key/gated plays only while you hold the pad. Legato is smooth note-to-note (good for melodic lines). Set per sound in sound edit."},
  {cat:"Sound edit",p:"My open and closed hi-hats ring over each other — how do I make them cut each other off?",
   d:"Put them in the same mute (choke) group in sound edit — triggering one silences the other, like a real hi-hat."},
  {cat:"Sound edit",p:"How do I stretch a sample to fit the tempo without changing its pitch?",
   d:"TIME (time-stretch) in sound edit matches the sample's BPM to the project. The time-stretch indicator lights when it's active. Heavily stretched material sounds cleaner on recent firmware."},

  /* ---- Timing & groove ---- */
  {cat:"Timing & groove",p:"How do I snap notes to the grid (quantize) — or turn it off?",
   d:"[TIMING], then [–]/[+] toggles quantize vs. free time. [SHIFT]+[TIMING] quantizes just one pad and leaves the rest."},
  {cat:"Timing & groove",p:"How do I change the step resolution (1/8, 1/16, triplets)?",
   d:"[TIMING] + turn [KNOB X]."},
  {cat:"Timing & groove",p:"How do I add swing / groove?",
   d:"[TIMING] + turn [KNOB Y] (affects 1/8 and 1/16 notes)."},
  {cat:"Timing & groove",p:"How do I get fast hi-hat rolls?",
   d:"Hold [TIMING] + a pad for note repeat. [TIMING] then [SHIFT]+pad latches it so you don't have to hold."},
  {cat:"Timing & groove",p:"How do I set the tempo precisely?",
   d:"[TEMPO] + turn [KNOB X], or hold [TEMPO] and type the BPM (40–399; use [·] for decimals). Tap [TEMPO] in rhythm for tap tempo."},
  {cat:"Timing & groove",p:"How do I change the time signature?",
   d:"[MAIN]+[TEMPO]."},

  /* ---- FX & mixing ---- */
  {cat:"FX & mixing",p:"How do I add reverb or delay to a part?",
   d:"[FX], [–]/[+] to choose the effect (delay, reverb, distortion, chorus, filter, or compressor), then raise the [FADER] to send the current group into it. One send effect per group."},
  {cat:"FX & mixing",p:"What are the punch-in effects and how do I use them?",
   d:"While playing, hold [FX] and the 12 pads become momentary, pressure-sensitive performance effects you can layer for live mangling. Hold [RECORD] while you perform them to bake the moves into the track."},
  {cat:"FX & mixing",p:"How do I solo one group to hear it on its own?",
   d:"Hold [FX] + that group pad (hold several to solo several). On recent firmware this also makes it the active edit group."},
  {cat:"FX & mixing",p:"My kick and bass are fighting / the low end is muddy",
   d:"Set up sidechain so the bass ducks when the kick hits: [SHIFT]+[FX] → [+] for sidechain; pick the source by holding a group pad and choosing a sound, then pick the destination groups with [SHIFT] + group pads."},
  {cat:"FX & mixing",p:"How do I make the whole track louder and more 'glued'?",
   d:"[SHIFT]+[FX] opens the output / master compressor."},
  {cat:"FX & mixing",p:"How do I record a filter sweep or a fader move?",
   d:"Assign what the fader controls (hold [FADER] + a pad — e.g., a filter or level), then hold [RECORD] while you move it. Undo just that automation with [ERASE]+[FADER]."},
  {cat:"FX & mixing",p:"How do I loop / stutter a section live?",
   d:"[SHIFT]+[TEMPO] drops a loop on the fly; hold [SHIFT]+[TEMPO] and release to set the loop length."},

  /* ---- Hardware & sync ---- */
  {cat:"Hardware & sync",p:"Where do headphones / speakers plug in?",
   d:"The 3.5 mm output jack carries line/headphone out. The separate input jack is for sampling instruments or other gear."},
  {cat:"Hardware & sync",p:"How do I sync the K.O. II to other gear?",
   d:"Over SYNC (PO-style pulse) or MIDI in/out via the TRS jacks and USB. It can be the clock leader or follow an external clock. (No built-in Bluetooth — wireless MIDI needs a third-party BLE adapter.)"},
  {cat:"Hardware & sync",p:"How do I power it? What batteries?",
   d:"USB-C, or 4× AAA batteries. Don't mix battery types (alkaline / rechargeable / carbon-zinc)."},
  {cat:"Hardware & sync",p:"The screen shows E.10, E.11 or E.12",c:"File-system error.",
   d:"Power off, then hold [SHIFT]+[ERASE] while powering on to format the drive (this erases your sounds). Update the firmware afterward."},
  {cat:"Hardware & sync",p:"The screen shows E.01, E.02 or E.03",c:"A hardware fault (memory/codec).",
   d:"This isn't a settings fix — the unit needs servicing by Teenage Engineering."},
  {cat:"Hardware & sync",p:"Nothing I press does anything",c:"You're probably in Lock mode (it engages if [MAIN] is held at power-up; 'LOK' flashes).",
   d:"Restart the unit to clear it."},
  {cat:"Hardware & sync",p:"How do I update the firmware?",
   d:"Connect over USB-C and go to teenage.engineering/apps/update. Updates have added real features (arpeggiator, better time-stretch, sidechain tweaks), so it's worth staying current."},
  {cat:"Hardware & sync",p:"How do I back up my projects?",
   d:"Connect over USB-C and use TE's tools to manage and back up your content. (Backup/restore has evolved across firmware — confirm the current method in the official guide before relying on it.)"},

  /* ---- Concepts — general guidance, not device documentation ---- */
  {cat:"Concepts",p:"What does 'quantize' actually mean, and when should I turn it off?",
   d:"Quantize snaps your notes onto the timing grid so everything lands 'on time'. It's great for tight electronic drums, but turning it off (free time) keeps the natural push-pull of a live performance — useful for swung hats, ghost notes, and anything that should feel human."},
  {cat:"Concepts",p:"What's a dead-simple drum pattern to start with?",
   d:"Four-on-the-floor: kick on every beat (1, 2, 3, 4). Add a snare or clap on beats 2 and 4 (the backbeat) and steady hats on the off-beats. That skeleton underlies most dance and pop music — build from there."},
  {cat:"Concepts",p:"Why does swing make a beat feel good?",
   d:"Swing delays every other subdivision slightly, so pairs of notes fall long-short instead of evenly. That tiny lag is what gives hip-hop and house their groove instead of a stiff, robotic feel. A little goes a long way."},
  {cat:"Concepts",p:"My loop feels repetitive after a few bars — how do I fix it?",
   d:"Introduce change: mute a part for a bar, add a fill at the end of every 4 or 8 bars, vary velocity, drop the bass out before a chorus, or bring an element in gradually. On the K.O. II, commit variations as new scenes and arrange them so the track evolves."},
  {cat:"Concepts",p:"How do I layer sounds for a bigger drum?",
   d:"Stack complementary samples on different pads and trigger them together — e.g., a deep kick for weight plus a clicky one for attack, or a snare plus a clap for body and snap. Trim and tune them so they hit as one."},
  {cat:"Concepts",p:"Why is my mix muddy, and how do I clean up the low end?",
   d:"Usually too much overlapping low frequency. Give the kick and bass their own space (sidechain the bass to the kick), keep only one main low-end element at a time, and pan mid/high sounds apart for width. On the K.O. II, sidechain lives under [SHIFT]+[FX]."},
  {cat:"Concepts",p:"What is gain staging, and how do I avoid clipping/distortion?",
   d:"Keep levels healthy but not maxed at every stage — sampling input, individual sounds, and the master. Leave a little headroom so peaks don't crackle. If a sample distorts, lower its level or the input gain rather than turning everything else down."},
  {cat:"Concepts",p:"How should I pan things for a wider mix?",
   d:"Keep the core (kick, snare, bass, lead vocal) centered, and spread supporting elements (hats, percussion, doubles) left and right. Small, tasteful moves usually beat hard extremes."},
  {cat:"Concepts",p:"How do I structure a whole song?",
   d:"Think in sections — intro, verse, build, chorus/drop, breakdown, outro — and create tension and release by adding and removing elements. On the K.O. II each section is a scene; chain them in song mode."},
  {cat:"Concepts",p:"What are ghost notes, and how do I use velocity for feel?",
   d:"Ghost notes are quiet hits between the main ones (soft snares/hats) that add groove. Vary velocity so accents land hard and in-betweens sit back — this is what separates a lifelike beat from a flat one. Turn on velocity (code 301) first."},
  {cat:"Concepts",p:"How do I actually finish a track instead of tweaking forever?",
   d:"Set a stopping point: arrange a full intro-to-outro pass, do one cleanup pass (levels, mutes, a fill or two), then export/record it and move on. Comparing to a reference track you love helps you decide when it's 'done' rather than chasing perfection."},
];
