/* =========================================================================
   KO II Coach — content layer
   Every device fact here targets the official teenage engineering EP-133
   K.O. II guide as of OS 2.5 (June 2026). Entries that could not be
   re-verified from this environment carry an `1` flag in the 4th slot and
   render with an "unverified" tag — see FIDELITY.md for the audit trail.
   ========================================================================= */

const META = {
  device: "EP-133 K.O. II",
  os: "2.5",
  checked: "2026-08",
  note: "content targets OS 2.5 — combos can change with firmware updates",
};

/* [category, keys, action, unverified?] */
const COMBOS = [
  ["Projects","Hold MAIN + pad 1–9","Switch to that project (a project = one song)"],
  ["Projects","Hold MAIN + pad 6–9","Open a factory-empty project to start clean (1–5 ship with demos)"],
  ["Scenes","Hold MAIN, then – / +","Move through scenes 01–99 (a scene = a section)"],
  ["Scenes","Hold MAIN + type a number","Jump straight to that scene"],
  ["Scenes","SHIFT + MAIN","Commit — freeze this scene and get a fresh copy to build on"],
  ["Song","Hold MAIN + ENTER","Open the song editor to chain scenes into an arrangement"],
  ["Song","SHIFT + GROUP A (in song editor)","Add a new scene slot to the song"],
  ["Song","SHIFT + – / + (in song editor)","Change which scene plays at this spot"],
  ["Song","SHIFT + PLAY","Play the whole song from the start"],
  ["Sounds","SOUND → group → pad","Pick a pad to load a sound onto"],
  ["Sounds","– / +  (in Sound)","Scroll samples on the selected pad"],
  ["Sounds","SHIFT + – / +  (in Sound)","Jump through samples ten at a time"],
  ["Sounds","Hold SOUND + type a number","Load a specific sample by number"],
  ["Sounds","Hold a pad (in Sound)","Preview the sample's name"],
  ["Sounds","SHIFT + SOUND","Sound Edit — trim, envelope, time-stretch, pan, play mode"],
  ["Sounds","Hold SHIFT + SOUND (2 sec)","Save your sound edits",1],
  ["Recording","Tap RECORD, then PLAY","Live record with a 4-beat count-in"],
  ["Recording","RECORD + PLAY together","Live record with no count-in"],
  ["Recording","Hold RECORD + a pad","Step-record that pad onto the current step"],
  ["Recording","RECORD, then SHIFT + PLAY","Record from the very start of the pattern"],
  ["Recording","Play, then hold RECORD + pads","Overdub onto a running pattern"],
  ["Recording","RECORD + ERASE + PLAY","Overwrite mode — replaces the old take as you record the new one"],
  ["Recording","Hold RECORD + move the FADER","Record fader (filter, level, etc.) movement"],
  ["Steps & length","Hold RECORD + – / +","Set pattern length (up to 99 bars)"],
  ["Steps & length","RECORD, then SHIFT + +","Duplicate the pattern and double its length"],
  ["Steps & length","– / +  (stopped)","Step forward / back through the pattern"],
  ["Steps & length","SHIFT + – / +","Move bar to bar"],
  ["Steps & length","Hold SHIFT + pad, then – / +","Nudge that note's timing"],
  ["Steps & length","Hold SHIFT + turn KNOB X","Set velocity of everything on the step"],
  ["Steps & length","Hold SHIFT + turn KNOB Y","Set note length on the step"],
  ["Keys","Select a pad, press KEYS","Play that sample across the pads like a keyboard"],
  ["Keys","Hold KEYS + – / +","Change octave"],
  ["Keys","Hold KEYS + a pad","Transpose — set the root note"],
  ["Keys","Hold TIMING + press pads (in Keys)","Arpeggiate the held pads — OS 2.5, one-shot & legato sounds"],
  ["Timing & groove","TIMING + turn KNOB X","Set the note interval (1/8, 1/16, triplets, 1/32…)"],
  ["Timing & groove","TIMING + turn KNOB Y","Add swing (works on 1/8 and 1/16)"],
  ["Timing & groove","TIMING, then – / +","Toggle quantize (–) vs free time (+)"],
  ["Timing & groove","Hold TIMING + a pad","Note repeat — perfect for hi-hats"],
  ["Timing & groove","TIMING, then SHIFT + pad","Latch note repeat on/off"],
  ["Timing & groove","SHIFT + TIMING","Timing Correct — quantize one pad, leave the rest"],
  ["Sampling","SAMPLE","Enter sample mode (the pads blink)"],
  ["Sampling","Hold a pad (in Sample)","Record to it; let go to stop (mono, up to 40 s on OS 2.5)"],
  ["Sampling","– / +  (in Sample)","Choose input: mic, line-in, resample, USB, L/R"],
  ["Sampling","Hold SHIFT + pad (in Sample)","Hands-free — the unit holds the pad for you"],
  ["Sampling","Hands-free, then PLAY","Resample the current pattern"],
  ["Sampling","SAMPLE (while recording)","Stop a hands-free sample"],
  ["Sampling","SHIFT + SAMPLE","Chop a sample across pads (auto or live)"],
  ["Sampling","In Chop: hold a group pad, then – / +","Choose auto-chop mode — EQU cuts equal-length slices (OS 2.5)"],
  ["Sampling","Hold SAMPLE + TEMPO","Detect incoming tempo and match the project to it"],
  ["Sampling","MAIN (in Sample)","Exit sample mode"],
  ["FX","FX (while playing)","Open the FX menu"],
  ["FX","– / +  (in FX)","Choose the effect"],
  ["FX","Move the FADER (in FX)","Set FX amount for the current group"],
  ["FX","Hold FX + a group pad","Solo that group (hold several to solo several)"],
  ["FX","Hold FX + pads","Punch-in FX — pressure-sensitive and combinable"],
  ["FX","SHIFT + FX","Output / master-compressor settings"],
  ["FX","SHIFT + FX, then +","Sidechain settings"],
  ["Copy · erase · undo","SHIFT + GROUP C","Copy (once = bar, twice = pattern)"],
  ["Copy · erase · undo","SHIFT + GROUP D","Paste"],
  ["Copy · erase · undo","SHIFT + GROUP B","Undo (umbrella lights when it's available)"],
  ["Copy · erase · undo","SHIFT + GROUP A","Jump to the next empty pattern"],
  ["Copy · erase · undo","Hold ERASE + a pad","Erase notes on that pad — even while playing"],
  ["Copy · erase · undo","Hold ERASE + a group pad","Erase the current pattern"],
  ["Copy · erase · undo","Hold ERASE + MAIN (2 sec)","Clear or delete the current scene",1],
  ["Copy · erase · undo","Hold ERASE + SOUND","Permanently delete the selected sample"],
  ["Copy · erase · undo","Hold ERASE + FADER","Erase the group's fader automation"],
  ["Tempo & loop","TEMPO","Enter tempo mode"],
  ["Tempo & loop","Tap TEMPO in rhythm","Tap tempo"],
  ["Tempo & loop","Hold TEMPO + type a number","Set exact BPM (40–399; use · for decimals)"],
  ["Tempo & loop","MAIN + TEMPO","Change the time signature"],
  ["Tempo & loop","SHIFT + TEMPO","Drop a loop (OB-4 style) on the fly"],
  ["Tempo & loop","Hold SHIFT + TEMPO","Set loop length — it ends when you let go"],
  ["Fader","Hold FADER + a pad","Assign the fader to the label above that pad (LEVEL, LPF, PAN…)"],
  ["Fader","Hold a group pad + move FADER","Set that group's overall volume"],
  ["Fader","SHIFT + FADER","Reset the fader's virtual position"],
  ["Sound Edit","SHIFT + SOUND","Enter Sound Edit — trim, envelope, pitch, play mode"],
  ["Sound Edit","Play mode (in Sound Edit)","Reverse a sample — flip its play direction (OS 2.5)"],
  ["System","SHIFT + ERASE","Open system settings"],
  ["System","Type 301 + ENTER","Pad velocity on, high sensitivity (ships off)"],
  ["System","Type 302 + ENTER","Pad velocity on, low sensitivity"],
  ["System","Type 300 + ENTER","Turn pad velocity off"],
  ["System","Type 400 + ENTER","Metronome on during record + play"],
  ["System","USB to computer / phone","Class-compliant USB audio in & out (OS 2.5)"],
  ["System","Hold MAIN while powering on","Lock mode — blocks changes until you restart"],
  ["System","Hold SHIFT + ERASE while powering on","Format the drive (fixes E.10–E.12; erases sounds)"],
];

const CTRL = {
  shift:{name:"SHIFT",sub:"the modifier",color:"#8f8778",
    blurb:"Held down, SHIFT unlocks a second function on almost every button — the small boxed label beneath it. It's the key to half the machine.",
    combos:[["SHIFT + SOUND","Sound Edit"],["SHIFT + MAIN","Commit a scene"],["SHIFT + SAMPLE","Chop"],["SHIFT + TEMPO","Drop a loop"],["SHIFT + ERASE","System settings"],["SHIFT + GROUP B","Undo"]]},
  sound:{name:"SOUND",sub:"assign & shape sounds",color:"#8f8778",
    blurb:"Where you put a sample on a pad and shape it. Pick a group, pick a pad, then scroll samples with – / +. SHIFT+SOUND opens deep editing — including reverse on OS 2.5.",
    combos:[["SOUND → group → pad","Choose a pad to load"],["– / +","Scroll samples"],["Hold SOUND + number","Load a specific sample"],["Hold a pad","Hear the sample's name"],["SHIFT + SOUND","Trim / envelope / time-stretch / reverse"]]},
  main:{name:"MAIN",sub:"home base",color:"#8f8778",
    blurb:"Your home screen — projects, scenes, patterns, recording and arranging all live here. Hold MAIN and the screen shows your scene (S.01…). When in doubt, press MAIN.",
    combos:[["Hold MAIN + pad 1–9","Switch project (song)"],["Hold MAIN + pad 6–9","Empty project"],["Hold MAIN, then – / +","Pick a scene"],["SHIFT + MAIN","Commit"],["Hold MAIN + ENTER","Song editor"]]},
  tempo:{name:"TEMPO",sub:"speed, loop & time-sig",color:"#8f8778",
    blurb:"Set the BPM by knob, by typing, or by tapping. Also hides the loop performance tool and the time signature.",
    combos:[["TEMPO + KNOB X","Set BPM"],["Tap TEMPO","Tap tempo"],["Hold TEMPO + number","Type exact BPM (40–399)"],["MAIN + TEMPO","Time signature"],["SHIFT + TEMPO","Loop"],["Hold SAMPLE + TEMPO","Match tempo to incoming audio"]]},
  sample:{name:"SAMPLE",sub:"record sound in",color:"var(--orange)",
    blurb:"Capture audio from the mic, the line-in (plug your guitar or phone in), USB, or by resampling the unit itself. Hold a pad to record onto it — mono, up to 40 seconds on OS 2.5. SHIFT+SAMPLE chops.",
    combos:[["SAMPLE","Enter sample mode"],["Hold a pad","Record; release to stop"],["– / +","Pick the input source"],["Hold SHIFT + pad","Hands-free recording"],["SHIFT + SAMPLE","Chop across pads"],["MAIN","Exit"]]},
  timing:{name:"TIMING",sub:"grid, swing & repeat",color:"#8f8778",
    blurb:"Sets the sequencer's note interval and swing, switches quantize on/off, and does note repeat when you hold it with a pad. In Keys mode it's also the arpeggiator (OS 2.5).",
    combos:[["TIMING + KNOB X","Note interval"],["TIMING + KNOB Y","Swing"],["TIMING, then – / +","Quantize vs free time"],["Hold TIMING + pad","Note repeat"],["SHIFT + TIMING","Quantize a single pad"],["In Keys: hold TIMING + pads","Arpeggiate (OS 2.5)"]]},
  keys:{name:"KEYS",sub:"play a sample melodically",color:"#8f8778",
    blurb:"Turns the pads into a chromatic keyboard for the selected sample — the fast way to play basslines and melodies. Hold TIMING with pads here to arpeggiate (OS 2.5).",
    combos:[["Select pad, press KEYS","Spread it across the pads"],["Hold KEYS + – / +","Octave"],["Hold KEYS + pad","Set the root note"],["Hold TIMING + pads","Arpeggiator (OS 2.5)"]]},
  fader:{name:"FADER",sub:"hands-on control",color:"#8f8778",
    blurb:"By default it's group volume. Reassign it and record its movement for automation. The silkscreen labels above the pads — LEVEL, PITCH, TIME, LPF, HPF, FX, ATK, REL, PAN, TUNE, VEL, MOD — are its possible destinations.",
    combos:[["Hold FADER + pad","Assign the label above that pad"],["Hold RECORD + move it","Record automation"],["Hold group pad + move it","Group volume"],["SHIFT + FADER","Reset it"]]},
  fx:{name:"FX",sub:"effects & punch-ins",color:"#8f8778",
    blurb:"Delay, reverb, distortion, chorus, filter, compressor — one per group via the fader. Hold FX and hit pads for live punch-in FX. SHIFT+FX is the master output.",
    combos:[["FX (playing)","Open FX"],["– / +","Choose the effect"],["Move FADER","FX amount"],["Hold FX + group","Solo it"],["Hold FX + pads","Punch-in FX"],["SHIFT + FX","Master compressor"]]},
  erase:{name:"ERASE",sub:"remove & undo territory",color:"#e9e7e0",
    blurb:"Removes notes, patterns, scenes or samples depending on what you hold it with. SHIFT+ERASE is the door to system settings.",
    combos:[["Hold ERASE + pad","Erase that pad's notes"],["Hold ERASE + group","Erase the pattern"],["Hold ERASE + MAIN (2s)","Clear the scene"],["Hold ERASE + SOUND","Delete the sample"],["SHIFT + ERASE","System settings"]]},
  groupa:{name:"GROUP A",sub:"suggested: drums",color:"var(--gA)",
    blurb:"One of four groups — think of each as an instrument with its own 12 pads and 99 patterns. A is the natural home for drums. The red tag is how it shows on the screen. Under SHIFT it's also 'next empty pattern'.",
    combos:[["Press A","Select the group"],["Hold A + – / +","Choose its pattern"],["SHIFT + A","Next empty pattern"],["Hold FX + A","Solo drums"]]},
  groupb:{name:"GROUP B",sub:"suggested: bass",color:"var(--gB)",
    blurb:"Second group — a good home for bass. Shows amber on the screen. Under SHIFT, GROUP B is your Undo button.",
    combos:[["Press B","Select the group"],["Hold B + – / +","Choose its pattern"],["SHIFT + B","Undo"],["Hold FX + B","Solo bass"]]},
  groupc:{name:"GROUP C",sub:"suggested: melody",color:"var(--gC)",
    blurb:"Third group — melodies and chords. Shows magenta on the screen. Under SHIFT, GROUP C is Copy.",
    combos:[["Press C","Select the group"],["Hold C + – / +","Choose its pattern"],["SHIFT + C","Copy (bar / pattern)"],["Hold FX + C","Solo melody"]]},
  groupd:{name:"GROUP D",sub:"suggested: your samples",color:"var(--gD)",
    blurb:"Fourth group — keep it empty for the sounds you sample yourself. Shows blue on the screen. Under SHIFT, GROUP D is Paste.",
    combos:[["Press D","Select the group"],["Hold D + – / +","Choose its pattern"],["SHIFT + D","Paste"],["Hold FX + D","Solo samples"]]},
  knobx:{name:"KNOB X",sub:"orange · context knob",color:"var(--orange)",
    blurb:"The context knob, sitting above SAMPLE. Its job changes per mode — BPM in tempo, note interval in timing, cutoff/drive in FX, amplitude in sound. Hold SHIFT while turning for fine control.",
    combos:[["In Tempo","BPM"],["In Timing","Note interval"],["In FX","First FX parameter"],["In Sound","Amplitude"],["Hold SHIFT + turn","Fine adjust"]]},
  knoby:{name:"KNOB Y",sub:"dark · context knob",color:"#8f8778",
    blurb:"The second context knob, above TIMING. Swing in timing, feedback/color in FX, pitch in sound, metronome volume in tempo. Hold SHIFT for fine control.",
    combos:[["In Timing","Swing"],["In FX","Second FX parameter"],["In Sound","Pitch"],["In Tempo","Metronome volume"],["Hold SHIFT + turn","Fine adjust"]]},
  volume:{name:"VOLUME",sub:"master output",color:"#8f8778",
    blurb:"Top-left knob — overall output level to the speaker and the output jack. Not part of any combo.",combos:[]},
  minus:{name:"MINUS  –",sub:"navigate down",color:"#e9e7e0",
    blurb:"With PLUS, the most-used pair on the unit: step through the sequencer, switch scenes and patterns, browse sounds and FX, nudge notes, change tempo.",
    combos:[["– (stopped)","Previous step"],["Hold MAIN + –","Previous scene"],["Hold RECORD + –","Shorten pattern"],["SHIFT + –","Previous bar"]]},
  plus:{name:"PLUS  +",sub:"navigate up",color:"#e9e7e0",
    blurb:"With MINUS, your main navigator: steps, scenes, patterns, sounds, FX, tempo and note nudging all run through it.",
    combos:[["+ (stopped)","Next step"],["Hold MAIN + +","Next scene"],["Hold RECORD + +","Lengthen pattern"],["SHIFT + +","Next bar"]]},
  record:{name:"RECORD",sub:"capture",color:"var(--orange)",
    blurb:"Arms recording. Tap it then PLAY for a counted-in live take, hit both together to skip the count, or hold it with a pad to place steps by hand.",
    combos:[["Tap RECORD, then PLAY","Live, with count-in"],["RECORD + PLAY","Live, no count-in"],["Hold RECORD + pad","Step-record"],["Hold RECORD + – / +","Pattern length"],["RECORD + ERASE + PLAY","Overwrite mode"]]},
  play:{name:"PLAY",sub:"start / stop",color:"#9a968c",
    blurb:"Starts and stops playback, bottom-right. Also the second half of most record moves.",
    combos:[["PLAY","Start / stop"],["RECORD, then PLAY","Record with count-in"],["SHIFT + PLAY","Play song from start"]]},
  enter:{name:"ENTER",sub:"confirm",color:"#8f8778",
    blurb:"Confirms typed values — sample numbers, system codes, tempo. Held with MAIN it opens the song editor.",
    combos:[["Type a code + ENTER","Confirm it"],["Hold MAIN + ENTER","Song editor"]]},
  pad:{name:"PADS  1–9, 0, ·",sub:"sounds + number pad",color:"#8f8778",
    blurb:"The 12 pads play your sounds and double as a number pad for typing values. The tiny silkscreen labels printed above each pad (LEVEL, PITCH, TIME, LPF…) are the fader destinations — assign one with FADER + that pad.",
    combos:[["Tap a pad","Play its sound"],["Hold RECORD + pad","Step-record it"],["Hold ERASE + pad","Erase its notes"],["Hold FADER + pad","Assign the fader"],["Type digits","Enter a number"]]},
};
["pad0","pad1","pad2","pad3","pad4","pad5","pad6","pad7","pad8","pad9","paddot"].forEach(k=>CTRL[k]=CTRL.pad);

/* Shift-box functions — opened by long-pressing the key that carries the box */
CTRL.sfedit={name:"EDIT",sub:"shift + sound · sound edit",color:"#e9e6df",
  blurb:"The boxed EDIT under SOUND. Hold SHIFT and press SOUND to open Sound Edit — trim start/end, shape the envelope, set pitch and time-stretch, pan, pick the play mode, and reverse a sample (OS 2.5).",
  combos:[["SHIFT + SOUND","Open Sound Edit"],["KNOB X / Y","Edit the shown parameter"],["– / +","Move between parameters"],["Play mode","One-shot, legato, loop… + reverse (OS 2.5)"],["Hold SHIFT + SOUND (2s)","Save the edits — unverified"]]};
CTRL.sfcommit={name:"COMMIT",sub:"shift + main · freeze a scene",color:"var(--orange)",
  blurb:"The orange COMMIT box under MAIN. SHIFT + MAIN freezes the current scene and hands you a fresh copy to keep building on — the K.O. II way to stack intro → verse → chorus without stopping.",
  combos:[["SHIFT + MAIN","Commit the scene"],["Hold MAIN, then – / +","Move between scenes"],["Hold MAIN + ENTER","Chain scenes in the song editor"]]};
CTRL.sfloop={name:"LOOP",sub:"shift + tempo · performance loop",color:"#b7b3aa",
  blurb:"The LOOP box under TEMPO. SHIFT + TEMPO drops an OB-4-style loop on the fly; hold the combo to set the loop length — it ends when you let go.",
  combos:[["SHIFT + TEMPO","Drop a loop"],["Hold SHIFT + TEMPO","Set loop length by holding"]]};
CTRL.sfchop={name:"CHOP",sub:"shift + sample · slice a sample",color:"#e9e6df",
  blurb:"The CHOP box under SAMPLE. SHIFT + SAMPLE slices a sample across a group's pads — automatically, evenly (EQU, OS 2.5), or live as you tap along.",
  combos:[["SHIFT + SAMPLE","Enter Chop"],["– / +","Number of slices"],["Hold a group pad, then – / +","Auto-chop mode — EQU = equal slices (OS 2.5)"],["Tap pads while playing","Live chop"],["KNOB X / Y","Fine-tune slice start / end"]]};
CTRL.sfcorrect={name:"CORRECT",sub:"shift + timing · fix one pad",color:"#e9e6df",
  blurb:"The CORRECT box under TIMING. SHIFT + TIMING opens Timing Correct — quantize the notes of a single pad and leave everything else exactly as you played it.",
  combos:[["SHIFT + TIMING","Timing Correct"],["Pick a pad","Quantize just that pad"]]};
CTRL.sfoutput={name:"OUTPUT",sub:"shift + fx · master section",color:"#e9e6df",
  blurb:"The OUTPUT box under FX. SHIFT + FX opens the master output settings — the master compressor, and the sidechain settings behind +.",
  combos:[["SHIFT + FX","Output / master compressor"],["then +","Sidechain settings"]]};
CTRL.sfsystem={name:"SYSTEM",sub:"shift + erase · settings",color:"#b7b3aa",
  blurb:"The SYSTEM box under ERASE. SHIFT + ERASE opens system settings — pad velocity, metronome, MIDI and sync, LED brightness, recording rates. Type a code and ENTER for quick access.",
  combos:[["SHIFT + ERASE","Open system settings"],["301 / 302 / 300 + ENTER","Velocity high / low / off"],["400 + ENTER","Metronome on"],["MIDI → Clock","Sync off / on / out"]]};

/* =========================================================================
   Display icons — the segment screen's indicators.
   The official guide documents 66 unique icons on this display; the set
   below is what could be verified from guide text in this environment
   (u:1 = plausible but not yet verified — see FIDELITY.md).
   ========================================================================= */
const DICONS = {
  groups:{name:"GROUP TAGS  A–D",sub:"who's playing",
    blurb:"The four group indicators. The active group's tag lights — red A, amber B, magenta C, blue D. This is where the group colors live on the real unit; the group keys themselves are grey."},
  digits:{name:"THE BIG NUMBER",sub:"the main readout",
    blurb:"The display's centerpiece. It shows whatever matters right now: the scene (S.01), the step position (1.1.1), the BPM, a sample number in Sound mode, system codes — and error codes (E.xx) if something's wrong."},
  bar:{name:"BAR",sub:"where you are in the pattern",
    blurb:"Lights with the current bar number while a pattern runs, so you always know where you are inside the loop — patterns can run up to 99 bars."},
  mode:{name:"MODE LABEL",sub:"where you are",u:1,
    blurb:"Shows the active mode — MAIN is home base; entering Sound, Sample, Tempo or FX takes over the display with that mode's readout. Press MAIN to come home."},
  rec:{name:"REC DOT",sub:"recording",
    blurb:"The red dot. Lit while the K.O. II is recording — live takes, step recording, fader automation, and hands-free sampling all light it."},
  play:{name:"PLAY",sub:"pattern running",u:1,
    blurb:"Lit while the sequencer runs. Playback starts and stops with the PLAY key, bottom-right of the unit."},
  q:{name:"Q · QUANTIZE",sub:"snap to the grid",u:1,
    blurb:"Quantize state. With quantize on, your hits snap to the note interval set in TIMING; press TIMING then – / + to switch between quantized and free time."},
  note:{name:"NOTE VALUE",sub:"the grid resolution",u:1,
    blurb:"Reflects the sequencer's note interval — 1/8, 1/16, triplets, 1/32 — set with TIMING + KNOB X. Swing (TIMING + KNOB Y) leans on 1/8 and 1/16."},
  metro:{name:"METRONOME",sub:"the click",
    blurb:"Blinks in time with the metronome. Turn the click on for record + play with system code 400; its volume is KNOB Y in Tempo mode."},
  keysic:{name:"KEYBOARD",sub:"keys mode",u:1,
    blurb:"Keys mode — the 12 pads become a chromatic keyboard for the selected sample. KEYS + – / + shifts octave; KEYS + a pad sets the root."},
  punch:{name:"PUNCH-IN FX",sub:"live effects",u:1,
    blurb:"Punch-in effects — hold FX and hit pads to throw effects at the running pattern, pressure-sensitive and stackable. The K.O. II's signature move."},
  loop:{name:"LOOP",sub:"performance loop",u:1,
    blurb:"The performance loop — SHIFT + TEMPO drops a loop on the fly; hold it to set the loop length. It ends when you let go."},
  umb:{name:"UMBRELLA",sub:"undo is available",
    blurb:"The famous umbrella — lit when an undo is available. SHIFT + GROUP B takes the last thing back. One level deep, so use it while it's lit."},
  batt:{name:"BATTERY",sub:"power source",
    blurb:"Lit when running on batteries; blinks when they're getting low. Disappears on USB power."},
  usb:{name:"USB",sub:"usb connection",
    blurb:"Lights when the K.O. II detects activity over USB — MIDI notes from a connected keyboard or computer, and on OS 2.5, USB audio in and out."},
  midi:{name:"MIDI",sub:"midi input",
    blurb:"Lights when incoming MIDI notes are detected. MIDI clock and sync behavior live in system settings (SHIFT + ERASE → MIDI)."},
  mic:{name:"MIC",sub:"sampling input",
    blurb:"Lit when the built-in microphone is the active sampling input. Pick the input with – / + inside Sample mode."},
  line:{name:"LINE-IN",sub:"sampling input",
    blurb:"Lit when the 3.5 mm line input is in use — your guitar, phone, or anything else you plug in. Mono, stereo, or single-channel L/R."},
  meter:{name:"LEVEL METER",sub:"low · mid · level",
    blurb:"A VU meter for the current signal — watch it while setting sampling gain with KNOB X so the take is hot but clean."},
  clip:{name:"CLIP",sub:"too hot",
    blurb:"Lights when the input clips. If you see it while sampling, back the gain off with KNOB X — a clipped take stays clipped."},
};


const RECIPES = [
  {t:"Your first beat, live",s:"New project to a committed loop in a minute",
   steps:[["Hold <span class='cmd'>MAIN + pad 6</span> for a clean, empty project."],
     ["Press <span class='cmd'>SOUND</span>, pick <b>GROUP A</b>, tap a pad, and dial in a kick with <span class='cmd'>– / +</span>. Fill a few pads with drums."],
     ["Press <span class='cmd'>MAIN</span>. Tap <span class='cmd'>RECORD</span> then <span class='cmd'>PLAY</span> — you'll hear a 4-beat count-in."],
     ["Play the pads to punch out a beat. Press <span class='cmd'>PLAY</span> to stop."],
     ["Happy with it? <span class='cmd'>SHIFT + MAIN</span> to commit it as a scene."]],
   tip:"Pads feel flat? Velocity ships <b>off</b>. Turn it on: <span class='cmd'>SHIFT + ERASE</span>, type <b>301</b>, ENTER (302 = low sensitivity)."},
  {t:"Program drums by step",s:"Place hits exactly, no timing skills needed",
   steps:[["In <b>MAIN</b>, hold <span class='cmd'>SHIFT + –</span> until the screen reads <b>1.1.1</b> — step one."],
     ["Hold <span class='cmd'>RECORD + a pad</span> to drop that sound on the step. It lights up."],
     ["Kick on <b>1.1.1 / 1.2.1 / 1.3.1 / 1.4.1</b> is a four-on-the-floor."],
     ["Snare on <b>1.2.1</b> and <b>1.4.1</b> is the backbeat."],
     ["For fast hats, hold <span class='cmd'>TIMING + a pad</span> to note-repeat them in."]],
   tip:"Set the grid first: <span class='cmd'>TIMING + KNOB X</span> for the note interval, <span class='cmd'>KNOB Y</span> for swing."},
  {t:"Sample your guitar",s:"Get a riff off the strings and into a pad",
   steps:[["Plug into the <b>3.5 mm input</b> (or just use the built-in mic)."],
     ["Select <b>GROUP D</b>, press <span class='cmd'>SAMPLE</span> — the pads blink."],
     ["Press <span class='cmd'>– / +</span> to choose <b>line-in</b>. Set the level with <span class='cmd'>KNOB X</span>."],
     ["Hold an empty pad and play your riff (mono, up to 40 s). Release to stop; tap the pad to hear it."],
     ["Press <span class='cmd'>MAIN</span> to drop back and sequence it like any other sound."]],
   tip:"Want it in time with your track? Hold <span class='cmd'>SAMPLE + TEMPO</span> and play — it'll detect the tempo and match the project."},
  {t:"Chop a loop into pieces",s:"Turn a break or phrase into playable slices",
   steps:[["Get a loop onto a pad (sample it or import it)."],
     ["Press <span class='cmd'>SHIFT + SAMPLE</span> to enter Chop."],
     ["Pick an <b>empty group</b> to hold the slices (this overwrites that group's pads)."],
     ["<b>Auto-chop:</b> <span class='cmd'>– / +</span> sets how many slices. On OS 2.5, hold a group pad and pick <b>EQU</b> with <span class='cmd'>– / +</span> for equal-length slices — ideal for breaks and vocals."],
     ["<b>Live chop:</b> tap pads in time as it plays to place cuts by hand."],
     ["Fine-tune any slice's start/end with <span class='cmd'>KNOB X / Y</span> (hold SHIFT for fine control)."]],
   tip:"Play the slices out of order until something grooves — that's where the magic usually hides."},
  {t:"Build a song with commit",s:"Stack sections without stopping the music",
   steps:[["Get a loop you like playing."],
     ["<span class='cmd'>SHIFT + MAIN</span> — commit. It freezes that scene and hands you a duplicate."],
     ["Change something on the copy: add a fill, mute a part, drop in a new sound."],
     ["Commit again. Repeat to stack intro → verse → chorus as separate scenes."],
     ["Hold <span class='cmd'>MAIN + ENTER</span> for the song editor and chain the scenes into order."]],
   tip:"Commit is not 'save to disk' — the unit auto-saves. It's 'snapshot this and give me a fresh copy to mess with.'"},
  {t:"Add movement with FX",s:"Punch-ins and automation for life and variation",
   steps:[["Press <span class='cmd'>FX</span> while playing, then <span class='cmd'>– / +</span> to pick delay, reverb, filter…"],
     ["Raise the <b>FADER</b> to send the current group into it."],
     ["Now hold <span class='cmd'>FX + pads</span> to punch effects in live — pressure-sensitive, and you can stack them."],
     ["To keep a move, hold <span class='cmd'>RECORD</span> while you do it — the fader/FX gets recorded in."]],
   tip:"Hold <span class='cmd'>FX + a group pad</span> to solo it while you dial the effect in on just that part."},
];

const FIXES = [
  {p:"My pads ignore how hard I hit them",c:"Velocity sensitivity is off from the factory.",
   d:"<span class='cmd'>SHIFT + ERASE</span>, type <b>301</b>, press <b>ENTER</b>. (302 = low sensitivity · 300 turns it back off.)"},
  {p:"Hold MAIN shows a scene, not my project",c:"That's correct — holding MAIN lands on scenes.",
   d:"– / + moves scenes <i>within</i> a song. To change songs, hold <span class='cmd'>MAIN + tap a number pad 1–9</span>."},
  {p:"I made a mistake — can I take it back?",c:"There's a single level of undo.",
   d:"<span class='cmd'>SHIFT + GROUP B</span>. The umbrella icon on screen lights up when an undo is available."},
  {p:"There's a wrong note in my pattern",c:"You can pull individual hits without re-recording.",
   d:"Hold <span class='cmd'>ERASE + that pad</span> — works while playing. Hold several pads to clear several at once."},
  {p:"I recorded junk over a whole part",c:"You can wipe a pattern or overwrite as you go.",
   d:"Wipe it: hold <span class='cmd'>ERASE + the group pad</span>. Or re-record over it: <span class='cmd'>RECORD + ERASE + PLAY</span> for overwrite mode."},
  {p:"A sample won't go away",c:"Samples live in one global library, not on the pad.",
   d:"In <b>SOUND</b> mode, select it, then hold <span class='cmd'>ERASE + SOUND</span> to delete it from the device for good."},
  {p:"Where did my sample even go?",c:"Every recording auto-saves to the next free slot.",
   d:"In <b>SOUND</b>, hold <span class='cmd'>SOUND</span> and type its number, or scroll with <span class='cmd'>– / +</span> to find it."},
  {p:"The screen shows E.10, E.11 or E.12",c:"File-system error — the drive needs formatting.",
   d:"Power off. Hold <span class='cmd'>SHIFT + ERASE</span> while powering on to format ('FMT' shows; this erases sounds). Then update the OS."},
  {p:"The screen shows E.01, E.02 or E.03",c:"Hardware fault (SRAM / flash / codec).",
   d:"This one isn't a settings fix — the unit needs servicing by Teenage Engineering."},
  {p:"Nothing I press does anything",c:"You're probably in Lock mode.",
   d:"Lock mode switches on when <b>MAIN</b> is held at power-up, and blocks all changes. Just restart the unit to clear it."},
  {p:"The tempo knob won't reach my BPM",c:"The knob only spans part of the range.",
   d:"Hold <span class='cmd'>TEMPO</span> and type the number for the full <b>40–399</b> range. Use <b>·</b> for decimals."},
  {p:"I want a totally clean slate",c:"You don't have to erase anything to start fresh.",
   d:"Hold <span class='cmd'>MAIN + a pad 6–9</span> for a factory-empty project. Your other projects stay untouched."},
];
